// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_network_flow_reports

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func NetworkFlowReportsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"network_flow_reports": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"created_at": schema.StringAttribute{
							Computed:            true,
							Description:         "The date and time, in UTC, the report was created. ISO 8601 Formatted.",
							MarkdownDescription: "The date and time, in UTC, the report was created. ISO 8601 Formatted.",
						},
						"created_by_token": schema.StringAttribute{
							Computed:            true,
							Description:         "The token for the User or Team that created this NetworkFlowReport.",
							MarkdownDescription: "The token for the User or Team that created this NetworkFlowReport.",
						},
						"date_interval": schema.StringAttribute{
							Computed:            true,
							Description:         "The date range for the NetworkFlowReport. Only present if a custom date range is not specified.",
							MarkdownDescription: "The date range for the NetworkFlowReport. Only present if a custom date range is not specified.",
						},
						"default": schema.BoolAttribute{
							Computed:            true,
							Description:         "Indicates whether the NetworkFlowReport is the default report.",
							MarkdownDescription: "Indicates whether the NetworkFlowReport is the default report.",
						},
						"end_date": schema.StringAttribute{
							Computed:            true,
							Description:         "The end date for the NetworkFlowReport. Only set for custom date ranges. ISO 8601 Formatted.",
							MarkdownDescription: "The end date for the NetworkFlowReport. Only set for custom date ranges. ISO 8601 Formatted.",
						},
						"filter": schema.StringAttribute{
							Computed:            true,
							Description:         "The filter applied to the NetworkFlowReport. Additional documentation available at https://docs.vantage.sh/vql.",
							MarkdownDescription: "The filter applied to the NetworkFlowReport. Additional documentation available at https://docs.vantage.sh/vql.",
						},
						"flow_direction": schema.StringAttribute{
							Computed:            true,
							Description:         "The flow weight of the NetworkFlowReport. Possible values: costs, bytes.",
							MarkdownDescription: "The flow weight of the NetworkFlowReport. Possible values: costs, bytes.",
						},
						"flow_weight": schema.StringAttribute{
							Computed:            true,
							Description:         "The flow weight of the NetworkFlowReport. Possible values: costs, bytes.",
							MarkdownDescription: "The flow weight of the NetworkFlowReport. Possible values: costs, bytes.",
						},
						"groupings": schema.StringAttribute{
							Computed:            true,
							Description:         "The grouping aggregations applied to the filtered data.",
							MarkdownDescription: "The grouping aggregations applied to the filtered data.",
						},
						"start_date": schema.StringAttribute{
							Computed:            true,
							Description:         "The start date for the NetworkFlowReport. Only set for custom date ranges. ISO 8601 Formatted.",
							MarkdownDescription: "The start date for the NetworkFlowReport. Only set for custom date ranges. ISO 8601 Formatted.",
						},
						"title": schema.StringAttribute{
							Computed:            true,
							Description:         "The title of the NetworkFlowReport.",
							MarkdownDescription: "The title of the NetworkFlowReport.",
						},
						"token": schema.StringAttribute{
							Computed: true,
						},
						"workspace_token": schema.StringAttribute{
							Computed:            true,
							Description:         "The token for the Workspace the NetworkFlowReport is a part of.",
							MarkdownDescription: "The token for the Workspace the NetworkFlowReport is a part of.",
						},
					},
					CustomType: NetworkFlowReportsType{
						ObjectType: types.ObjectType{
							AttrTypes: NetworkFlowReportsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
		},
	}
}

type NetworkFlowReportsModel struct {
	NetworkFlowReports types.List `tfsdk:"network_flow_reports"`
}

var _ basetypes.ObjectTypable = NetworkFlowReportsType{}

type NetworkFlowReportsType struct {
	basetypes.ObjectType
}

func (t NetworkFlowReportsType) Equal(o attr.Type) bool {
	other, ok := o.(NetworkFlowReportsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t NetworkFlowReportsType) String() string {
	return "NetworkFlowReportsType"
}

func (t NetworkFlowReportsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return nil, diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	createdByTokenAttribute, ok := attributes["created_by_token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_by_token is missing from object`)

		return nil, diags
	}

	createdByTokenVal, ok := createdByTokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_by_token expected to be basetypes.StringValue, was: %T`, createdByTokenAttribute))
	}

	dateIntervalAttribute, ok := attributes["date_interval"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`date_interval is missing from object`)

		return nil, diags
	}

	dateIntervalVal, ok := dateIntervalAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`date_interval expected to be basetypes.StringValue, was: %T`, dateIntervalAttribute))
	}

	defaultAttribute, ok := attributes["default"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`default is missing from object`)

		return nil, diags
	}

	defaultVal, ok := defaultAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`default expected to be basetypes.BoolValue, was: %T`, defaultAttribute))
	}

	endDateAttribute, ok := attributes["end_date"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`end_date is missing from object`)

		return nil, diags
	}

	endDateVal, ok := endDateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`end_date expected to be basetypes.StringValue, was: %T`, endDateAttribute))
	}

	filterAttribute, ok := attributes["filter"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`filter is missing from object`)

		return nil, diags
	}

	filterVal, ok := filterAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`filter expected to be basetypes.StringValue, was: %T`, filterAttribute))
	}

	flowDirectionAttribute, ok := attributes["flow_direction"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`flow_direction is missing from object`)

		return nil, diags
	}

	flowDirectionVal, ok := flowDirectionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`flow_direction expected to be basetypes.StringValue, was: %T`, flowDirectionAttribute))
	}

	flowWeightAttribute, ok := attributes["flow_weight"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`flow_weight is missing from object`)

		return nil, diags
	}

	flowWeightVal, ok := flowWeightAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`flow_weight expected to be basetypes.StringValue, was: %T`, flowWeightAttribute))
	}

	groupingsAttribute, ok := attributes["groupings"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`groupings is missing from object`)

		return nil, diags
	}

	groupingsVal, ok := groupingsAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`groupings expected to be basetypes.StringValue, was: %T`, groupingsAttribute))
	}

	startDateAttribute, ok := attributes["start_date"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`start_date is missing from object`)

		return nil, diags
	}

	startDateVal, ok := startDateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`start_date expected to be basetypes.StringValue, was: %T`, startDateAttribute))
	}

	titleAttribute, ok := attributes["title"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`title is missing from object`)

		return nil, diags
	}

	titleVal, ok := titleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`title expected to be basetypes.StringValue, was: %T`, titleAttribute))
	}

	tokenAttribute, ok := attributes["token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`token is missing from object`)

		return nil, diags
	}

	tokenVal, ok := tokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`token expected to be basetypes.StringValue, was: %T`, tokenAttribute))
	}

	workspaceTokenAttribute, ok := attributes["workspace_token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`workspace_token is missing from object`)

		return nil, diags
	}

	workspaceTokenVal, ok := workspaceTokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`workspace_token expected to be basetypes.StringValue, was: %T`, workspaceTokenAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return NetworkFlowReportsValue{
		CreatedAt:      createdAtVal,
		CreatedByToken: createdByTokenVal,
		DateInterval:   dateIntervalVal,
		Default:        defaultVal,
		EndDate:        endDateVal,
		Filter:         filterVal,
		FlowDirection:  flowDirectionVal,
		FlowWeight:     flowWeightVal,
		Groupings:      groupingsVal,
		StartDate:      startDateVal,
		Title:          titleVal,
		Token:          tokenVal,
		WorkspaceToken: workspaceTokenVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewNetworkFlowReportsValueNull() NetworkFlowReportsValue {
	return NetworkFlowReportsValue{
		state: attr.ValueStateNull,
	}
}

func NewNetworkFlowReportsValueUnknown() NetworkFlowReportsValue {
	return NetworkFlowReportsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewNetworkFlowReportsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (NetworkFlowReportsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing NetworkFlowReportsValue Attribute Value",
				"While creating a NetworkFlowReportsValue value, a missing attribute value was detected. "+
					"A NetworkFlowReportsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("NetworkFlowReportsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid NetworkFlowReportsValue Attribute Type",
				"While creating a NetworkFlowReportsValue value, an invalid attribute value was detected. "+
					"A NetworkFlowReportsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("NetworkFlowReportsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("NetworkFlowReportsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra NetworkFlowReportsValue Attribute Value",
				"While creating a NetworkFlowReportsValue value, an extra attribute value was detected. "+
					"A NetworkFlowReportsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra NetworkFlowReportsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewNetworkFlowReportsValueUnknown(), diags
	}

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return NewNetworkFlowReportsValueUnknown(), diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	createdByTokenAttribute, ok := attributes["created_by_token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_by_token is missing from object`)

		return NewNetworkFlowReportsValueUnknown(), diags
	}

	createdByTokenVal, ok := createdByTokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_by_token expected to be basetypes.StringValue, was: %T`, createdByTokenAttribute))
	}

	dateIntervalAttribute, ok := attributes["date_interval"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`date_interval is missing from object`)

		return NewNetworkFlowReportsValueUnknown(), diags
	}

	dateIntervalVal, ok := dateIntervalAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`date_interval expected to be basetypes.StringValue, was: %T`, dateIntervalAttribute))
	}

	defaultAttribute, ok := attributes["default"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`default is missing from object`)

		return NewNetworkFlowReportsValueUnknown(), diags
	}

	defaultVal, ok := defaultAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`default expected to be basetypes.BoolValue, was: %T`, defaultAttribute))
	}

	endDateAttribute, ok := attributes["end_date"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`end_date is missing from object`)

		return NewNetworkFlowReportsValueUnknown(), diags
	}

	endDateVal, ok := endDateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`end_date expected to be basetypes.StringValue, was: %T`, endDateAttribute))
	}

	filterAttribute, ok := attributes["filter"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`filter is missing from object`)

		return NewNetworkFlowReportsValueUnknown(), diags
	}

	filterVal, ok := filterAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`filter expected to be basetypes.StringValue, was: %T`, filterAttribute))
	}

	flowDirectionAttribute, ok := attributes["flow_direction"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`flow_direction is missing from object`)

		return NewNetworkFlowReportsValueUnknown(), diags
	}

	flowDirectionVal, ok := flowDirectionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`flow_direction expected to be basetypes.StringValue, was: %T`, flowDirectionAttribute))
	}

	flowWeightAttribute, ok := attributes["flow_weight"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`flow_weight is missing from object`)

		return NewNetworkFlowReportsValueUnknown(), diags
	}

	flowWeightVal, ok := flowWeightAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`flow_weight expected to be basetypes.StringValue, was: %T`, flowWeightAttribute))
	}

	groupingsAttribute, ok := attributes["groupings"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`groupings is missing from object`)

		return NewNetworkFlowReportsValueUnknown(), diags
	}

	groupingsVal, ok := groupingsAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`groupings expected to be basetypes.StringValue, was: %T`, groupingsAttribute))
	}

	startDateAttribute, ok := attributes["start_date"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`start_date is missing from object`)

		return NewNetworkFlowReportsValueUnknown(), diags
	}

	startDateVal, ok := startDateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`start_date expected to be basetypes.StringValue, was: %T`, startDateAttribute))
	}

	titleAttribute, ok := attributes["title"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`title is missing from object`)

		return NewNetworkFlowReportsValueUnknown(), diags
	}

	titleVal, ok := titleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`title expected to be basetypes.StringValue, was: %T`, titleAttribute))
	}

	tokenAttribute, ok := attributes["token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`token is missing from object`)

		return NewNetworkFlowReportsValueUnknown(), diags
	}

	tokenVal, ok := tokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`token expected to be basetypes.StringValue, was: %T`, tokenAttribute))
	}

	workspaceTokenAttribute, ok := attributes["workspace_token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`workspace_token is missing from object`)

		return NewNetworkFlowReportsValueUnknown(), diags
	}

	workspaceTokenVal, ok := workspaceTokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`workspace_token expected to be basetypes.StringValue, was: %T`, workspaceTokenAttribute))
	}

	if diags.HasError() {
		return NewNetworkFlowReportsValueUnknown(), diags
	}

	return NetworkFlowReportsValue{
		CreatedAt:      createdAtVal,
		CreatedByToken: createdByTokenVal,
		DateInterval:   dateIntervalVal,
		Default:        defaultVal,
		EndDate:        endDateVal,
		Filter:         filterVal,
		FlowDirection:  flowDirectionVal,
		FlowWeight:     flowWeightVal,
		Groupings:      groupingsVal,
		StartDate:      startDateVal,
		Title:          titleVal,
		Token:          tokenVal,
		WorkspaceToken: workspaceTokenVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewNetworkFlowReportsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) NetworkFlowReportsValue {
	object, diags := NewNetworkFlowReportsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewNetworkFlowReportsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t NetworkFlowReportsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewNetworkFlowReportsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewNetworkFlowReportsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewNetworkFlowReportsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewNetworkFlowReportsValueMust(NetworkFlowReportsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t NetworkFlowReportsType) ValueType(ctx context.Context) attr.Value {
	return NetworkFlowReportsValue{}
}

var _ basetypes.ObjectValuable = NetworkFlowReportsValue{}

type NetworkFlowReportsValue struct {
	CreatedAt      basetypes.StringValue `tfsdk:"created_at"`
	CreatedByToken basetypes.StringValue `tfsdk:"created_by_token"`
	DateInterval   basetypes.StringValue `tfsdk:"date_interval"`
	Default        basetypes.BoolValue   `tfsdk:"default"`
	EndDate        basetypes.StringValue `tfsdk:"end_date"`
	Filter         basetypes.StringValue `tfsdk:"filter"`
	FlowDirection  basetypes.StringValue `tfsdk:"flow_direction"`
	FlowWeight     basetypes.StringValue `tfsdk:"flow_weight"`
	Groupings      basetypes.StringValue `tfsdk:"groupings"`
	StartDate      basetypes.StringValue `tfsdk:"start_date"`
	Title          basetypes.StringValue `tfsdk:"title"`
	Token          basetypes.StringValue `tfsdk:"token"`
	WorkspaceToken basetypes.StringValue `tfsdk:"workspace_token"`
	state          attr.ValueState
}

func (v NetworkFlowReportsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 13)

	var val tftypes.Value
	var err error

	attrTypes["created_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["created_by_token"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["date_interval"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["default"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["end_date"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["filter"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["flow_direction"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["flow_weight"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["groupings"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["start_date"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["title"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["token"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["workspace_token"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 13)

		val, err = v.CreatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created_at"] = val

		val, err = v.CreatedByToken.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created_by_token"] = val

		val, err = v.DateInterval.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["date_interval"] = val

		val, err = v.Default.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["default"] = val

		val, err = v.EndDate.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["end_date"] = val

		val, err = v.Filter.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["filter"] = val

		val, err = v.FlowDirection.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["flow_direction"] = val

		val, err = v.FlowWeight.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["flow_weight"] = val

		val, err = v.Groupings.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["groupings"] = val

		val, err = v.StartDate.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["start_date"] = val

		val, err = v.Title.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["title"] = val

		val, err = v.Token.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["token"] = val

		val, err = v.WorkspaceToken.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["workspace_token"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v NetworkFlowReportsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v NetworkFlowReportsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v NetworkFlowReportsValue) String() string {
	return "NetworkFlowReportsValue"
}

func (v NetworkFlowReportsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"created_at":       basetypes.StringType{},
		"created_by_token": basetypes.StringType{},
		"date_interval":    basetypes.StringType{},
		"default":          basetypes.BoolType{},
		"end_date":         basetypes.StringType{},
		"filter":           basetypes.StringType{},
		"flow_direction":   basetypes.StringType{},
		"flow_weight":      basetypes.StringType{},
		"groupings":        basetypes.StringType{},
		"start_date":       basetypes.StringType{},
		"title":            basetypes.StringType{},
		"token":            basetypes.StringType{},
		"workspace_token":  basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"created_at":       v.CreatedAt,
			"created_by_token": v.CreatedByToken,
			"date_interval":    v.DateInterval,
			"default":          v.Default,
			"end_date":         v.EndDate,
			"filter":           v.Filter,
			"flow_direction":   v.FlowDirection,
			"flow_weight":      v.FlowWeight,
			"groupings":        v.Groupings,
			"start_date":       v.StartDate,
			"title":            v.Title,
			"token":            v.Token,
			"workspace_token":  v.WorkspaceToken,
		})

	return objVal, diags
}

func (v NetworkFlowReportsValue) Equal(o attr.Value) bool {
	other, ok := o.(NetworkFlowReportsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.CreatedAt.Equal(other.CreatedAt) {
		return false
	}

	if !v.CreatedByToken.Equal(other.CreatedByToken) {
		return false
	}

	if !v.DateInterval.Equal(other.DateInterval) {
		return false
	}

	if !v.Default.Equal(other.Default) {
		return false
	}

	if !v.EndDate.Equal(other.EndDate) {
		return false
	}

	if !v.Filter.Equal(other.Filter) {
		return false
	}

	if !v.FlowDirection.Equal(other.FlowDirection) {
		return false
	}

	if !v.FlowWeight.Equal(other.FlowWeight) {
		return false
	}

	if !v.Groupings.Equal(other.Groupings) {
		return false
	}

	if !v.StartDate.Equal(other.StartDate) {
		return false
	}

	if !v.Title.Equal(other.Title) {
		return false
	}

	if !v.Token.Equal(other.Token) {
		return false
	}

	if !v.WorkspaceToken.Equal(other.WorkspaceToken) {
		return false
	}

	return true
}

func (v NetworkFlowReportsValue) Type(ctx context.Context) attr.Type {
	return NetworkFlowReportsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v NetworkFlowReportsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"created_at":       basetypes.StringType{},
		"created_by_token": basetypes.StringType{},
		"date_interval":    basetypes.StringType{},
		"default":          basetypes.BoolType{},
		"end_date":         basetypes.StringType{},
		"filter":           basetypes.StringType{},
		"flow_direction":   basetypes.StringType{},
		"flow_weight":      basetypes.StringType{},
		"groupings":        basetypes.StringType{},
		"start_date":       basetypes.StringType{},
		"title":            basetypes.StringType{},
		"token":            basetypes.StringType{},
		"workspace_token":  basetypes.StringType{},
	}
}
