// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_budgets

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func BudgetsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"budgets": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"budget_alert_tokens": schema.ListAttribute{
							ElementType:         types.StringType,
							Computed:            true,
							Description:         "The tokens of the BudgetAlerts associated with the Budget.",
							MarkdownDescription: "The tokens of the BudgetAlerts associated with the Budget.",
						},
						"child_budget_tokens": schema.ListAttribute{
							ElementType:         types.StringType,
							Computed:            true,
							Description:         "The tokens of the child Budgets associated with the hierarchical Budget.",
							MarkdownDescription: "The tokens of the child Budgets associated with the hierarchical Budget.",
						},
						"cost_report_token": schema.StringAttribute{
							Computed:            true,
							Description:         "The token of the Report associated with the Budget.",
							MarkdownDescription: "The token of the Report associated with the Budget.",
						},
						"created_at": schema.StringAttribute{
							Computed:            true,
							Description:         "The date and time, in UTC, the Budget was created. ISO 8601 Formatted.",
							MarkdownDescription: "The date and time, in UTC, the Budget was created. ISO 8601 Formatted.",
						},
						"created_by_token": schema.StringAttribute{
							Computed:            true,
							Description:         "The token of the Creator of the Budget.",
							MarkdownDescription: "The token of the Creator of the Budget.",
						},
						"id": schema.StringAttribute{
							Computed:            true,
							Description:         "The id of the resource",
							MarkdownDescription: "The id of the resource",
						},
						"name": schema.StringAttribute{
							Computed:            true,
							Description:         "The name of the Budget.",
							MarkdownDescription: "The name of the Budget.",
						},
						"performance": schema.ListNestedAttribute{
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"actual": schema.StringAttribute{
										Computed:            true,
										Description:         "The date and time, in UTC, the Budget was created. ISO 8601 Formatted.",
										MarkdownDescription: "The date and time, in UTC, the Budget was created. ISO 8601 Formatted.",
									},
									"amount": schema.StringAttribute{
										Computed:            true,
										Description:         "The amount of the Budget Period as a string to ensure precision.",
										MarkdownDescription: "The amount of the Budget Period as a string to ensure precision.",
									},
									"date": schema.StringAttribute{
										Computed:            true,
										Description:         "The date and time, in UTC, the Budget was created. ISO 8601 Formatted.",
										MarkdownDescription: "The date and time, in UTC, the Budget was created. ISO 8601 Formatted.",
									},
								},
								CustomType: PerformanceType{
									ObjectType: types.ObjectType{
										AttrTypes: PerformanceValue{}.AttributeTypes(ctx),
									},
								},
							},
							Computed:            true,
							Description:         "The historical performance of the Budget.",
							MarkdownDescription: "The historical performance of the Budget.",
						},
						"periods": schema.ListNestedAttribute{
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"amount": schema.StringAttribute{
										Computed:            true,
										Description:         "The amount of the Budget Period as a string to ensure precision.",
										MarkdownDescription: "The amount of the Budget Period as a string to ensure precision.",
									},
									"end_at": schema.StringAttribute{
										Computed:            true,
										Description:         "The date and time, in UTC, the Budget was created. ISO 8601 Formatted.",
										MarkdownDescription: "The date and time, in UTC, the Budget was created. ISO 8601 Formatted.",
									},
									"start_at": schema.StringAttribute{
										Computed:            true,
										Description:         "The date and time, in UTC, the Budget was created. ISO 8601 Formatted.",
										MarkdownDescription: "The date and time, in UTC, the Budget was created. ISO 8601 Formatted.",
									},
								},
								CustomType: PeriodsType{
									ObjectType: types.ObjectType{
										AttrTypes: PeriodsValue{}.AttributeTypes(ctx),
									},
								},
							},
							Computed:            true,
							Description:         "The budget periods associated with the Budget.",
							MarkdownDescription: "The budget periods associated with the Budget.",
						},
						"token": schema.StringAttribute{
							Computed: true,
						},
						"user_token": schema.StringAttribute{
							Computed:            true,
							Description:         "The token for the User who created this Budget.",
							MarkdownDescription: "The token for the User who created this Budget.",
						},
						"workspace_token": schema.StringAttribute{
							Computed:            true,
							Description:         "The token for the Workspace the Budget is a part of.",
							MarkdownDescription: "The token for the Workspace the Budget is a part of.",
						},
					},
					CustomType: BudgetsType{
						ObjectType: types.ObjectType{
							AttrTypes: BudgetsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
		},
	}
}

type BudgetsModel struct {
	Budgets types.List `tfsdk:"budgets"`
}

var _ basetypes.ObjectTypable = BudgetsType{}

type BudgetsType struct {
	basetypes.ObjectType
}

func (t BudgetsType) Equal(o attr.Type) bool {
	other, ok := o.(BudgetsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t BudgetsType) String() string {
	return "BudgetsType"
}

func (t BudgetsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	budgetAlertTokensAttribute, ok := attributes["budget_alert_tokens"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`budget_alert_tokens is missing from object`)

		return nil, diags
	}

	budgetAlertTokensVal, ok := budgetAlertTokensAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`budget_alert_tokens expected to be basetypes.ListValue, was: %T`, budgetAlertTokensAttribute))
	}

	childBudgetTokensAttribute, ok := attributes["child_budget_tokens"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`child_budget_tokens is missing from object`)

		return nil, diags
	}

	childBudgetTokensVal, ok := childBudgetTokensAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`child_budget_tokens expected to be basetypes.ListValue, was: %T`, childBudgetTokensAttribute))
	}

	costReportTokenAttribute, ok := attributes["cost_report_token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cost_report_token is missing from object`)

		return nil, diags
	}

	costReportTokenVal, ok := costReportTokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cost_report_token expected to be basetypes.StringValue, was: %T`, costReportTokenAttribute))
	}

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return nil, diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	createdByTokenAttribute, ok := attributes["created_by_token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_by_token is missing from object`)

		return nil, diags
	}

	createdByTokenVal, ok := createdByTokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_by_token expected to be basetypes.StringValue, was: %T`, createdByTokenAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	performanceAttribute, ok := attributes["performance"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`performance is missing from object`)

		return nil, diags
	}

	performanceVal, ok := performanceAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`performance expected to be basetypes.ListValue, was: %T`, performanceAttribute))
	}

	periodsAttribute, ok := attributes["periods"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`periods is missing from object`)

		return nil, diags
	}

	periodsVal, ok := periodsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`periods expected to be basetypes.ListValue, was: %T`, periodsAttribute))
	}

	tokenAttribute, ok := attributes["token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`token is missing from object`)

		return nil, diags
	}

	tokenVal, ok := tokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`token expected to be basetypes.StringValue, was: %T`, tokenAttribute))
	}

	userTokenAttribute, ok := attributes["user_token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`user_token is missing from object`)

		return nil, diags
	}

	userTokenVal, ok := userTokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`user_token expected to be basetypes.StringValue, was: %T`, userTokenAttribute))
	}

	workspaceTokenAttribute, ok := attributes["workspace_token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`workspace_token is missing from object`)

		return nil, diags
	}

	workspaceTokenVal, ok := workspaceTokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`workspace_token expected to be basetypes.StringValue, was: %T`, workspaceTokenAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return BudgetsValue{
		BudgetAlertTokens: budgetAlertTokensVal,
		ChildBudgetTokens: childBudgetTokensVal,
		CostReportToken:   costReportTokenVal,
		CreatedAt:         createdAtVal,
		CreatedByToken:    createdByTokenVal,
		Id:                idVal,
		Name:              nameVal,
		Performance:       performanceVal,
		Periods:           periodsVal,
		Token:             tokenVal,
		UserToken:         userTokenVal,
		WorkspaceToken:    workspaceTokenVal,
		state:             attr.ValueStateKnown,
	}, diags
}

func NewBudgetsValueNull() BudgetsValue {
	return BudgetsValue{
		state: attr.ValueStateNull,
	}
}

func NewBudgetsValueUnknown() BudgetsValue {
	return BudgetsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewBudgetsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (BudgetsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing BudgetsValue Attribute Value",
				"While creating a BudgetsValue value, a missing attribute value was detected. "+
					"A BudgetsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("BudgetsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid BudgetsValue Attribute Type",
				"While creating a BudgetsValue value, an invalid attribute value was detected. "+
					"A BudgetsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("BudgetsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("BudgetsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra BudgetsValue Attribute Value",
				"While creating a BudgetsValue value, an extra attribute value was detected. "+
					"A BudgetsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra BudgetsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewBudgetsValueUnknown(), diags
	}

	budgetAlertTokensAttribute, ok := attributes["budget_alert_tokens"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`budget_alert_tokens is missing from object`)

		return NewBudgetsValueUnknown(), diags
	}

	budgetAlertTokensVal, ok := budgetAlertTokensAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`budget_alert_tokens expected to be basetypes.ListValue, was: %T`, budgetAlertTokensAttribute))
	}

	childBudgetTokensAttribute, ok := attributes["child_budget_tokens"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`child_budget_tokens is missing from object`)

		return NewBudgetsValueUnknown(), diags
	}

	childBudgetTokensVal, ok := childBudgetTokensAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`child_budget_tokens expected to be basetypes.ListValue, was: %T`, childBudgetTokensAttribute))
	}

	costReportTokenAttribute, ok := attributes["cost_report_token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cost_report_token is missing from object`)

		return NewBudgetsValueUnknown(), diags
	}

	costReportTokenVal, ok := costReportTokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cost_report_token expected to be basetypes.StringValue, was: %T`, costReportTokenAttribute))
	}

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return NewBudgetsValueUnknown(), diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	createdByTokenAttribute, ok := attributes["created_by_token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_by_token is missing from object`)

		return NewBudgetsValueUnknown(), diags
	}

	createdByTokenVal, ok := createdByTokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_by_token expected to be basetypes.StringValue, was: %T`, createdByTokenAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewBudgetsValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewBudgetsValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	performanceAttribute, ok := attributes["performance"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`performance is missing from object`)

		return NewBudgetsValueUnknown(), diags
	}

	performanceVal, ok := performanceAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`performance expected to be basetypes.ListValue, was: %T`, performanceAttribute))
	}

	periodsAttribute, ok := attributes["periods"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`periods is missing from object`)

		return NewBudgetsValueUnknown(), diags
	}

	periodsVal, ok := periodsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`periods expected to be basetypes.ListValue, was: %T`, periodsAttribute))
	}

	tokenAttribute, ok := attributes["token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`token is missing from object`)

		return NewBudgetsValueUnknown(), diags
	}

	tokenVal, ok := tokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`token expected to be basetypes.StringValue, was: %T`, tokenAttribute))
	}

	userTokenAttribute, ok := attributes["user_token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`user_token is missing from object`)

		return NewBudgetsValueUnknown(), diags
	}

	userTokenVal, ok := userTokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`user_token expected to be basetypes.StringValue, was: %T`, userTokenAttribute))
	}

	workspaceTokenAttribute, ok := attributes["workspace_token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`workspace_token is missing from object`)

		return NewBudgetsValueUnknown(), diags
	}

	workspaceTokenVal, ok := workspaceTokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`workspace_token expected to be basetypes.StringValue, was: %T`, workspaceTokenAttribute))
	}

	if diags.HasError() {
		return NewBudgetsValueUnknown(), diags
	}

	return BudgetsValue{
		BudgetAlertTokens: budgetAlertTokensVal,
		ChildBudgetTokens: childBudgetTokensVal,
		CostReportToken:   costReportTokenVal,
		CreatedAt:         createdAtVal,
		CreatedByToken:    createdByTokenVal,
		Id:                idVal,
		Name:              nameVal,
		Performance:       performanceVal,
		Periods:           periodsVal,
		Token:             tokenVal,
		UserToken:         userTokenVal,
		WorkspaceToken:    workspaceTokenVal,
		state:             attr.ValueStateKnown,
	}, diags
}

func NewBudgetsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) BudgetsValue {
	object, diags := NewBudgetsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewBudgetsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t BudgetsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewBudgetsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewBudgetsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewBudgetsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewBudgetsValueMust(BudgetsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t BudgetsType) ValueType(ctx context.Context) attr.Value {
	return BudgetsValue{}
}

var _ basetypes.ObjectValuable = BudgetsValue{}

type BudgetsValue struct {
	BudgetAlertTokens basetypes.ListValue   `tfsdk:"budget_alert_tokens"`
	ChildBudgetTokens basetypes.ListValue   `tfsdk:"child_budget_tokens"`
	CostReportToken   basetypes.StringValue `tfsdk:"cost_report_token"`
	CreatedAt         basetypes.StringValue `tfsdk:"created_at"`
	CreatedByToken    basetypes.StringValue `tfsdk:"created_by_token"`
	Id                basetypes.StringValue `tfsdk:"id"`
	Name              basetypes.StringValue `tfsdk:"name"`
	Performance       basetypes.ListValue   `tfsdk:"performance"`
	Periods           basetypes.ListValue   `tfsdk:"periods"`
	Token             basetypes.StringValue `tfsdk:"token"`
	UserToken         basetypes.StringValue `tfsdk:"user_token"`
	WorkspaceToken    basetypes.StringValue `tfsdk:"workspace_token"`
	state             attr.ValueState
}

func (v BudgetsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 12)

	var val tftypes.Value
	var err error

	attrTypes["budget_alert_tokens"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["child_budget_tokens"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["cost_report_token"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["created_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["created_by_token"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["performance"] = basetypes.ListType{
		ElemType: PerformanceValue{}.Type(ctx),
	}.TerraformType(ctx)
	attrTypes["periods"] = basetypes.ListType{
		ElemType: PeriodsValue{}.Type(ctx),
	}.TerraformType(ctx)
	attrTypes["token"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["user_token"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["workspace_token"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 12)

		val, err = v.BudgetAlertTokens.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["budget_alert_tokens"] = val

		val, err = v.ChildBudgetTokens.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["child_budget_tokens"] = val

		val, err = v.CostReportToken.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["cost_report_token"] = val

		val, err = v.CreatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created_at"] = val

		val, err = v.CreatedByToken.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created_by_token"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Performance.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["performance"] = val

		val, err = v.Periods.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["periods"] = val

		val, err = v.Token.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["token"] = val

		val, err = v.UserToken.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["user_token"] = val

		val, err = v.WorkspaceToken.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["workspace_token"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v BudgetsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v BudgetsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v BudgetsValue) String() string {
	return "BudgetsValue"
}

func (v BudgetsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	performance := types.ListValueMust(
		PerformanceType{
			basetypes.ObjectType{
				AttrTypes: PerformanceValue{}.AttributeTypes(ctx),
			},
		},
		v.Performance.Elements(),
	)

	if v.Performance.IsNull() {
		performance = types.ListNull(
			PerformanceType{
				basetypes.ObjectType{
					AttrTypes: PerformanceValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	if v.Performance.IsUnknown() {
		performance = types.ListUnknown(
			PerformanceType{
				basetypes.ObjectType{
					AttrTypes: PerformanceValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	periods := types.ListValueMust(
		PeriodsType{
			basetypes.ObjectType{
				AttrTypes: PeriodsValue{}.AttributeTypes(ctx),
			},
		},
		v.Periods.Elements(),
	)

	if v.Periods.IsNull() {
		periods = types.ListNull(
			PeriodsType{
				basetypes.ObjectType{
					AttrTypes: PeriodsValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	if v.Periods.IsUnknown() {
		periods = types.ListUnknown(
			PeriodsType{
				basetypes.ObjectType{
					AttrTypes: PeriodsValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	budgetAlertTokensVal := types.ListValueMust(types.StringType, v.BudgetAlertTokens.Elements())

	if v.BudgetAlertTokens.IsNull() {
		budgetAlertTokensVal = types.ListNull(types.StringType)
	}

	if v.BudgetAlertTokens.IsUnknown() {
		budgetAlertTokensVal = types.ListUnknown(types.StringType)
	}

	childBudgetTokensVal := types.ListValueMust(types.StringType, v.ChildBudgetTokens.Elements())

	if v.ChildBudgetTokens.IsNull() {
		childBudgetTokensVal = types.ListNull(types.StringType)
	}

	if v.ChildBudgetTokens.IsUnknown() {
		childBudgetTokensVal = types.ListUnknown(types.StringType)
	}

	objVal, diags := types.ObjectValue(
		map[string]attr.Type{
			"budget_alert_tokens": basetypes.ListType{
				ElemType: types.StringType,
			},
			"child_budget_tokens": basetypes.ListType{
				ElemType: types.StringType,
			},
			"cost_report_token": basetypes.StringType{},
			"created_at":        basetypes.StringType{},
			"created_by_token":  basetypes.StringType{},
			"id":                basetypes.StringType{},
			"name":              basetypes.StringType{},
			"performance": basetypes.ListType{
				ElemType: PerformanceValue{}.Type(ctx),
			},
			"periods": basetypes.ListType{
				ElemType: PeriodsValue{}.Type(ctx),
			},
			"token":           basetypes.StringType{},
			"user_token":      basetypes.StringType{},
			"workspace_token": basetypes.StringType{},
		},
		map[string]attr.Value{
			"budget_alert_tokens": budgetAlertTokensVal,
			"child_budget_tokens": childBudgetTokensVal,
			"cost_report_token":   v.CostReportToken,
			"created_at":          v.CreatedAt,
			"created_by_token":    v.CreatedByToken,
			"id":                  v.Id,
			"name":                v.Name,
			"performance":         performance,
			"periods":             periods,
			"token":               v.Token,
			"user_token":          v.UserToken,
			"workspace_token":     v.WorkspaceToken,
		})

	return objVal, diags
}

func (v BudgetsValue) Equal(o attr.Value) bool {
	other, ok := o.(BudgetsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.BudgetAlertTokens.Equal(other.BudgetAlertTokens) {
		return false
	}

	if !v.ChildBudgetTokens.Equal(other.ChildBudgetTokens) {
		return false
	}

	if !v.CostReportToken.Equal(other.CostReportToken) {
		return false
	}

	if !v.CreatedAt.Equal(other.CreatedAt) {
		return false
	}

	if !v.CreatedByToken.Equal(other.CreatedByToken) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Performance.Equal(other.Performance) {
		return false
	}

	if !v.Periods.Equal(other.Periods) {
		return false
	}

	if !v.Token.Equal(other.Token) {
		return false
	}

	if !v.UserToken.Equal(other.UserToken) {
		return false
	}

	if !v.WorkspaceToken.Equal(other.WorkspaceToken) {
		return false
	}

	return true
}

func (v BudgetsValue) Type(ctx context.Context) attr.Type {
	return BudgetsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v BudgetsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"budget_alert_tokens": basetypes.ListType{
			ElemType: types.StringType,
		},
		"child_budget_tokens": basetypes.ListType{
			ElemType: types.StringType,
		},
		"cost_report_token": basetypes.StringType{},
		"created_at":        basetypes.StringType{},
		"created_by_token":  basetypes.StringType{},
		"id":                basetypes.StringType{},
		"name":              basetypes.StringType{},
		"performance": basetypes.ListType{
			ElemType: PerformanceValue{}.Type(ctx),
		},
		"periods": basetypes.ListType{
			ElemType: PeriodsValue{}.Type(ctx),
		},
		"token":           basetypes.StringType{},
		"user_token":      basetypes.StringType{},
		"workspace_token": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = PerformanceType{}

type PerformanceType struct {
	basetypes.ObjectType
}

func (t PerformanceType) Equal(o attr.Type) bool {
	other, ok := o.(PerformanceType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t PerformanceType) String() string {
	return "PerformanceType"
}

func (t PerformanceType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	actualAttribute, ok := attributes["actual"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`actual is missing from object`)

		return nil, diags
	}

	actualVal, ok := actualAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`actual expected to be basetypes.StringValue, was: %T`, actualAttribute))
	}

	amountAttribute, ok := attributes["amount"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`amount is missing from object`)

		return nil, diags
	}

	amountVal, ok := amountAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`amount expected to be basetypes.StringValue, was: %T`, amountAttribute))
	}

	dateAttribute, ok := attributes["date"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`date is missing from object`)

		return nil, diags
	}

	dateVal, ok := dateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`date expected to be basetypes.StringValue, was: %T`, dateAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return PerformanceValue{
		Actual: actualVal,
		Amount: amountVal,
		Date:   dateVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewPerformanceValueNull() PerformanceValue {
	return PerformanceValue{
		state: attr.ValueStateNull,
	}
}

func NewPerformanceValueUnknown() PerformanceValue {
	return PerformanceValue{
		state: attr.ValueStateUnknown,
	}
}

func NewPerformanceValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (PerformanceValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing PerformanceValue Attribute Value",
				"While creating a PerformanceValue value, a missing attribute value was detected. "+
					"A PerformanceValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PerformanceValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid PerformanceValue Attribute Type",
				"While creating a PerformanceValue value, an invalid attribute value was detected. "+
					"A PerformanceValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PerformanceValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("PerformanceValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra PerformanceValue Attribute Value",
				"While creating a PerformanceValue value, an extra attribute value was detected. "+
					"A PerformanceValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra PerformanceValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewPerformanceValueUnknown(), diags
	}

	actualAttribute, ok := attributes["actual"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`actual is missing from object`)

		return NewPerformanceValueUnknown(), diags
	}

	actualVal, ok := actualAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`actual expected to be basetypes.StringValue, was: %T`, actualAttribute))
	}

	amountAttribute, ok := attributes["amount"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`amount is missing from object`)

		return NewPerformanceValueUnknown(), diags
	}

	amountVal, ok := amountAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`amount expected to be basetypes.StringValue, was: %T`, amountAttribute))
	}

	dateAttribute, ok := attributes["date"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`date is missing from object`)

		return NewPerformanceValueUnknown(), diags
	}

	dateVal, ok := dateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`date expected to be basetypes.StringValue, was: %T`, dateAttribute))
	}

	if diags.HasError() {
		return NewPerformanceValueUnknown(), diags
	}

	return PerformanceValue{
		Actual: actualVal,
		Amount: amountVal,
		Date:   dateVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewPerformanceValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) PerformanceValue {
	object, diags := NewPerformanceValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewPerformanceValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t PerformanceType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewPerformanceValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewPerformanceValueUnknown(), nil
	}

	if in.IsNull() {
		return NewPerformanceValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewPerformanceValueMust(PerformanceValue{}.AttributeTypes(ctx), attributes), nil
}

func (t PerformanceType) ValueType(ctx context.Context) attr.Value {
	return PerformanceValue{}
}

var _ basetypes.ObjectValuable = PerformanceValue{}

type PerformanceValue struct {
	Actual basetypes.StringValue `tfsdk:"actual"`
	Amount basetypes.StringValue `tfsdk:"amount"`
	Date   basetypes.StringValue `tfsdk:"date"`
	state  attr.ValueState
}

func (v PerformanceValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["actual"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["amount"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["date"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Actual.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["actual"] = val

		val, err = v.Amount.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["amount"] = val

		val, err = v.Date.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["date"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v PerformanceValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v PerformanceValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v PerformanceValue) String() string {
	return "PerformanceValue"
}

func (v PerformanceValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	objVal, diags := types.ObjectValue(
		map[string]attr.Type{
			"actual": basetypes.StringType{},
			"amount": basetypes.StringType{},
			"date":   basetypes.StringType{},
		},
		map[string]attr.Value{
			"actual": v.Actual,
			"amount": v.Amount,
			"date":   v.Date,
		})

	return objVal, diags
}

func (v PerformanceValue) Equal(o attr.Value) bool {
	other, ok := o.(PerformanceValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Actual.Equal(other.Actual) {
		return false
	}

	if !v.Amount.Equal(other.Amount) {
		return false
	}

	if !v.Date.Equal(other.Date) {
		return false
	}

	return true
}

func (v PerformanceValue) Type(ctx context.Context) attr.Type {
	return PerformanceType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v PerformanceValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"actual": basetypes.StringType{},
		"amount": basetypes.StringType{},
		"date":   basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = PeriodsType{}

type PeriodsType struct {
	basetypes.ObjectType
}

func (t PeriodsType) Equal(o attr.Type) bool {
	other, ok := o.(PeriodsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t PeriodsType) String() string {
	return "PeriodsType"
}

func (t PeriodsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	amountAttribute, ok := attributes["amount"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`amount is missing from object`)

		return nil, diags
	}

	amountVal, ok := amountAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`amount expected to be basetypes.StringValue, was: %T`, amountAttribute))
	}

	endAtAttribute, ok := attributes["end_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`end_at is missing from object`)

		return nil, diags
	}

	endAtVal, ok := endAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`end_at expected to be basetypes.StringValue, was: %T`, endAtAttribute))
	}

	startAtAttribute, ok := attributes["start_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`start_at is missing from object`)

		return nil, diags
	}

	startAtVal, ok := startAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`start_at expected to be basetypes.StringValue, was: %T`, startAtAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return PeriodsValue{
		Amount:  amountVal,
		EndAt:   endAtVal,
		StartAt: startAtVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewPeriodsValueNull() PeriodsValue {
	return PeriodsValue{
		state: attr.ValueStateNull,
	}
}

func NewPeriodsValueUnknown() PeriodsValue {
	return PeriodsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewPeriodsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (PeriodsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing PeriodsValue Attribute Value",
				"While creating a PeriodsValue value, a missing attribute value was detected. "+
					"A PeriodsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PeriodsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid PeriodsValue Attribute Type",
				"While creating a PeriodsValue value, an invalid attribute value was detected. "+
					"A PeriodsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PeriodsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("PeriodsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra PeriodsValue Attribute Value",
				"While creating a PeriodsValue value, an extra attribute value was detected. "+
					"A PeriodsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra PeriodsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewPeriodsValueUnknown(), diags
	}

	amountAttribute, ok := attributes["amount"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`amount is missing from object`)

		return NewPeriodsValueUnknown(), diags
	}

	amountVal, ok := amountAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`amount expected to be basetypes.StringValue, was: %T`, amountAttribute))
	}

	endAtAttribute, ok := attributes["end_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`end_at is missing from object`)

		return NewPeriodsValueUnknown(), diags
	}

	endAtVal, ok := endAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`end_at expected to be basetypes.StringValue, was: %T`, endAtAttribute))
	}

	startAtAttribute, ok := attributes["start_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`start_at is missing from object`)

		return NewPeriodsValueUnknown(), diags
	}

	startAtVal, ok := startAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`start_at expected to be basetypes.StringValue, was: %T`, startAtAttribute))
	}

	if diags.HasError() {
		return NewPeriodsValueUnknown(), diags
	}

	return PeriodsValue{
		Amount:  amountVal,
		EndAt:   endAtVal,
		StartAt: startAtVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewPeriodsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) PeriodsValue {
	object, diags := NewPeriodsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewPeriodsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t PeriodsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewPeriodsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewPeriodsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewPeriodsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewPeriodsValueMust(PeriodsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t PeriodsType) ValueType(ctx context.Context) attr.Value {
	return PeriodsValue{}
}

var _ basetypes.ObjectValuable = PeriodsValue{}

type PeriodsValue struct {
	Amount  basetypes.StringValue `tfsdk:"amount"`
	EndAt   basetypes.StringValue `tfsdk:"end_at"`
	StartAt basetypes.StringValue `tfsdk:"start_at"`
	state   attr.ValueState
}

func (v PeriodsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["amount"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["end_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["start_at"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Amount.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["amount"] = val

		val, err = v.EndAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["end_at"] = val

		val, err = v.StartAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["start_at"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v PeriodsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v PeriodsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v PeriodsValue) String() string {
	return "PeriodsValue"
}

func (v PeriodsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	objVal, diags := types.ObjectValue(
		map[string]attr.Type{
			"amount":   basetypes.StringType{},
			"end_at":   basetypes.StringType{},
			"start_at": basetypes.StringType{},
		},
		map[string]attr.Value{
			"amount":   v.Amount,
			"end_at":   v.EndAt,
			"start_at": v.StartAt,
		})

	return objVal, diags
}

func (v PeriodsValue) Equal(o attr.Value) bool {
	other, ok := o.(PeriodsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Amount.Equal(other.Amount) {
		return false
	}

	if !v.EndAt.Equal(other.EndAt) {
		return false
	}

	if !v.StartAt.Equal(other.StartAt) {
		return false
	}

	return true
}

func (v PeriodsValue) Type(ctx context.Context) attr.Type {
	return PeriodsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v PeriodsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"amount":   basetypes.StringType{},
		"end_at":   basetypes.StringType{},
		"start_at": basetypes.StringType{},
	}
}
