// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_enrichment_sources

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func EnrichmentSourcesDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"enrichment_sources": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"active": schema.BoolAttribute{
							Computed:            true,
							Description:         "Whether the EnrichmentSource is active.",
							MarkdownDescription: "Whether the EnrichmentSource is active.",
						},
						"created_at": schema.StringAttribute{
							Computed:            true,
							Description:         "The date and time, in UTC, the EnrichmentSource was created. ISO 8601 Formatted.",
							MarkdownDescription: "The date and time, in UTC, the EnrichmentSource was created. ISO 8601 Formatted.",
						},
						"id": schema.StringAttribute{
							Computed:            true,
							Description:         "The id of the resource",
							MarkdownDescription: "The id of the resource",
						},
						"integration_token": schema.StringAttribute{
							Computed:            true,
							Description:         "The token for the Integration that owns this EnrichmentSource.",
							MarkdownDescription: "The token for the Integration that owns this EnrichmentSource.",
						},
						"title": schema.StringAttribute{
							Computed:            true,
							Description:         "The display name for the enrichment source type.",
							MarkdownDescription: "The display name for the enrichment source type.",
						},
						"token": schema.StringAttribute{
							Computed:            true,
							Description:         "The token for the EnrichmentSource.",
							MarkdownDescription: "The token for the EnrichmentSource.",
						},
						"type": schema.StringAttribute{
							Computed:            true,
							Description:         "The enrichment source type.",
							MarkdownDescription: "The enrichment source type.",
						},
					},
					CustomType: EnrichmentSourcesType{
						ObjectType: types.ObjectType{
							AttrTypes: EnrichmentSourcesValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
		},
	}
}

type EnrichmentSourcesModel struct {
	EnrichmentSources types.List `tfsdk:"enrichment_sources"`
}

var _ basetypes.ObjectTypable = EnrichmentSourcesType{}

type EnrichmentSourcesType struct {
	basetypes.ObjectType
}

func (t EnrichmentSourcesType) Equal(o attr.Type) bool {
	other, ok := o.(EnrichmentSourcesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t EnrichmentSourcesType) String() string {
	return "EnrichmentSourcesType"
}

func (t EnrichmentSourcesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	activeAttribute, ok := attributes["active"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`active is missing from object`)

		return nil, diags
	}

	activeVal, ok := activeAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`active expected to be basetypes.BoolValue, was: %T`, activeAttribute))
	}

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return nil, diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	integrationTokenAttribute, ok := attributes["integration_token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`integration_token is missing from object`)

		return nil, diags
	}

	integrationTokenVal, ok := integrationTokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`integration_token expected to be basetypes.StringValue, was: %T`, integrationTokenAttribute))
	}

	titleAttribute, ok := attributes["title"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`title is missing from object`)

		return nil, diags
	}

	titleVal, ok := titleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`title expected to be basetypes.StringValue, was: %T`, titleAttribute))
	}

	tokenAttribute, ok := attributes["token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`token is missing from object`)

		return nil, diags
	}

	tokenVal, ok := tokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`token expected to be basetypes.StringValue, was: %T`, tokenAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return EnrichmentSourcesValue{
		Active:                activeVal,
		CreatedAt:             createdAtVal,
		Id:                    idVal,
		IntegrationToken:      integrationTokenVal,
		Title:                 titleVal,
		Token:                 tokenVal,
		EnrichmentSourcesType: typeVal,
		state:                 attr.ValueStateKnown,
	}, diags
}

func NewEnrichmentSourcesValueNull() EnrichmentSourcesValue {
	return EnrichmentSourcesValue{
		state: attr.ValueStateNull,
	}
}

func NewEnrichmentSourcesValueUnknown() EnrichmentSourcesValue {
	return EnrichmentSourcesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewEnrichmentSourcesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (EnrichmentSourcesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing EnrichmentSourcesValue Attribute Value",
				"While creating a EnrichmentSourcesValue value, a missing attribute value was detected. "+
					"A EnrichmentSourcesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("EnrichmentSourcesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid EnrichmentSourcesValue Attribute Type",
				"While creating a EnrichmentSourcesValue value, an invalid attribute value was detected. "+
					"A EnrichmentSourcesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("EnrichmentSourcesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("EnrichmentSourcesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra EnrichmentSourcesValue Attribute Value",
				"While creating a EnrichmentSourcesValue value, an extra attribute value was detected. "+
					"A EnrichmentSourcesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra EnrichmentSourcesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewEnrichmentSourcesValueUnknown(), diags
	}

	activeAttribute, ok := attributes["active"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`active is missing from object`)

		return NewEnrichmentSourcesValueUnknown(), diags
	}

	activeVal, ok := activeAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`active expected to be basetypes.BoolValue, was: %T`, activeAttribute))
	}

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return NewEnrichmentSourcesValueUnknown(), diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewEnrichmentSourcesValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	integrationTokenAttribute, ok := attributes["integration_token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`integration_token is missing from object`)

		return NewEnrichmentSourcesValueUnknown(), diags
	}

	integrationTokenVal, ok := integrationTokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`integration_token expected to be basetypes.StringValue, was: %T`, integrationTokenAttribute))
	}

	titleAttribute, ok := attributes["title"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`title is missing from object`)

		return NewEnrichmentSourcesValueUnknown(), diags
	}

	titleVal, ok := titleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`title expected to be basetypes.StringValue, was: %T`, titleAttribute))
	}

	tokenAttribute, ok := attributes["token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`token is missing from object`)

		return NewEnrichmentSourcesValueUnknown(), diags
	}

	tokenVal, ok := tokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`token expected to be basetypes.StringValue, was: %T`, tokenAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewEnrichmentSourcesValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewEnrichmentSourcesValueUnknown(), diags
	}

	return EnrichmentSourcesValue{
		Active:                activeVal,
		CreatedAt:             createdAtVal,
		Id:                    idVal,
		IntegrationToken:      integrationTokenVal,
		Title:                 titleVal,
		Token:                 tokenVal,
		EnrichmentSourcesType: typeVal,
		state:                 attr.ValueStateKnown,
	}, diags
}

func NewEnrichmentSourcesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) EnrichmentSourcesValue {
	object, diags := NewEnrichmentSourcesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewEnrichmentSourcesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t EnrichmentSourcesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewEnrichmentSourcesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewEnrichmentSourcesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewEnrichmentSourcesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewEnrichmentSourcesValueMust(EnrichmentSourcesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t EnrichmentSourcesType) ValueType(ctx context.Context) attr.Value {
	return EnrichmentSourcesValue{}
}

var _ basetypes.ObjectValuable = EnrichmentSourcesValue{}

type EnrichmentSourcesValue struct {
	Active                basetypes.BoolValue   `tfsdk:"active"`
	CreatedAt             basetypes.StringValue `tfsdk:"created_at"`
	Id                    basetypes.StringValue `tfsdk:"id"`
	IntegrationToken      basetypes.StringValue `tfsdk:"integration_token"`
	Title                 basetypes.StringValue `tfsdk:"title"`
	Token                 basetypes.StringValue `tfsdk:"token"`
	EnrichmentSourcesType basetypes.StringValue `tfsdk:"type"`
	state                 attr.ValueState
}

func (v EnrichmentSourcesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 7)

	var val tftypes.Value
	var err error

	attrTypes["active"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["created_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["integration_token"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["title"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["token"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 7)

		val, err = v.Active.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["active"] = val

		val, err = v.CreatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created_at"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.IntegrationToken.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["integration_token"] = val

		val, err = v.Title.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["title"] = val

		val, err = v.Token.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["token"] = val

		val, err = v.EnrichmentSourcesType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v EnrichmentSourcesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v EnrichmentSourcesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v EnrichmentSourcesValue) String() string {
	return "EnrichmentSourcesValue"
}

func (v EnrichmentSourcesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"active":            basetypes.BoolType{},
		"created_at":        basetypes.StringType{},
		"id":                basetypes.StringType{},
		"integration_token": basetypes.StringType{},
		"title":             basetypes.StringType{},
		"token":             basetypes.StringType{},
		"type":              basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"active":            v.Active,
			"created_at":        v.CreatedAt,
			"id":                v.Id,
			"integration_token": v.IntegrationToken,
			"title":             v.Title,
			"token":             v.Token,
			"type":              v.EnrichmentSourcesType,
		})

	return objVal, diags
}

func (v EnrichmentSourcesValue) Equal(o attr.Value) bool {
	other, ok := o.(EnrichmentSourcesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Active.Equal(other.Active) {
		return false
	}

	if !v.CreatedAt.Equal(other.CreatedAt) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.IntegrationToken.Equal(other.IntegrationToken) {
		return false
	}

	if !v.Title.Equal(other.Title) {
		return false
	}

	if !v.Token.Equal(other.Token) {
		return false
	}

	if !v.EnrichmentSourcesType.Equal(other.EnrichmentSourcesType) {
		return false
	}

	return true
}

func (v EnrichmentSourcesValue) Type(ctx context.Context) attr.Type {
	return EnrichmentSourcesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v EnrichmentSourcesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"active":            basetypes.BoolType{},
		"created_at":        basetypes.StringType{},
		"id":                basetypes.StringType{},
		"integration_token": basetypes.StringType{},
		"title":             basetypes.StringType{},
		"token":             basetypes.StringType{},
		"type":              basetypes.StringType{},
	}
}
