// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_anomaly_notification

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func AnomalyNotificationResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"cost_report_token": schema.StringAttribute{
				Required:            true,
				Description:         "The token of the Cost Report that has the notification.",
				MarkdownDescription: "The token of the Cost Report that has the notification.",
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "The date and time, in UTC, the AnomalyNotification was created. ISO 8601 Formatted.",
				MarkdownDescription: "The date and time, in UTC, the AnomalyNotification was created. ISO 8601 Formatted.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The id of the report alert",
				MarkdownDescription: "The id of the report alert",
			},
			"recipient_channels": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "The Slack/MS Teams channels that receive the notification.",
				MarkdownDescription: "The Slack/MS Teams channels that receive the notification.",
			},
			"threshold": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The threshold amount that must be met for the notification to fire.",
				MarkdownDescription: "The threshold amount that must be met for the notification to fire.",
			},
			"token": schema.StringAttribute{
				Computed:            true,
				Description:         "The token of the report alert",
				MarkdownDescription: "The token of the report alert",
			},
			"updated_at": schema.StringAttribute{
				Computed:            true,
				Description:         "The date and time, in UTC, the AnomalyNotification was last updated at. ISO 8601 Formatted.",
				MarkdownDescription: "The date and time, in UTC, the AnomalyNotification was last updated at. ISO 8601 Formatted.",
			},
			"user_tokens": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "The tokens of the Users that receive the notification.",
				MarkdownDescription: "The tokens of the Users that receive the notification.",
			},
		},
	}
}

type AnomalyNotificationModel struct {
	CostReportToken   types.String `tfsdk:"cost_report_token"`
	CreatedAt         types.String `tfsdk:"created_at"`
	Id                types.String `tfsdk:"id"`
	RecipientChannels types.List   `tfsdk:"recipient_channels"`
	Threshold         types.Int64  `tfsdk:"threshold"`
	Token             types.String `tfsdk:"token"`
	UpdatedAt         types.String `tfsdk:"updated_at"`
	UserTokens        types.List   `tfsdk:"user_tokens"`
}
