// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_business_metrics

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func BusinessMetricsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"business_metrics": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"cost_report_tokens_with_metadata": schema.ListNestedAttribute{
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"cost_report_token": schema.StringAttribute{
										Computed:            true,
										Description:         "The token of the CostReport the BusinessMetric is attached to.",
										MarkdownDescription: "The token of the CostReport the BusinessMetric is attached to.",
									},
									"label_filter": schema.ListAttribute{
										ElementType:         types.StringType,
										Computed:            true,
										Description:         "The labels that the BusinessMetric is filtered by within a particular CostReport.",
										MarkdownDescription: "The labels that the BusinessMetric is filtered by within a particular CostReport.",
									},
									"unit_scale": schema.StringAttribute{
										Computed:            true,
										Description:         "Determines the scale of the BusinessMetric's values within a particular CostReport.",
										MarkdownDescription: "Determines the scale of the BusinessMetric's values within a particular CostReport.",
									},
								},
								CustomType: CostReportTokensWithMetadataType{
									ObjectType: types.ObjectType{
										AttrTypes: CostReportTokensWithMetadataValue{}.AttributeTypes(ctx),
									},
								},
							},
							Computed:            true,
							Description:         "The tokens for any CostReports that use the BusinessMetric, the unit scale, and label filter.",
							MarkdownDescription: "The tokens for any CostReports that use the BusinessMetric, the unit scale, and label filter.",
						},
						"created_by_token": schema.StringAttribute{
							Computed:            true,
							Description:         "The token of the Creator of the BusinessMetric.",
							MarkdownDescription: "The token of the Creator of the BusinessMetric.",
						},
						"title": schema.StringAttribute{
							Computed:            true,
							Description:         "The title of the BusinessMetric.",
							MarkdownDescription: "The title of the BusinessMetric.",
						},
						"token": schema.StringAttribute{
							Computed:            true,
							Description:         "The token of the BusinessMetric.",
							MarkdownDescription: "The token of the BusinessMetric.",
						},
					},
					CustomType: BusinessMetricsType{
						ObjectType: types.ObjectType{
							AttrTypes: BusinessMetricsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
		},
	}
}

type BusinessMetricsModel struct {
	BusinessMetrics types.List `tfsdk:"business_metrics"`
}

var _ basetypes.ObjectTypable = BusinessMetricsType{}

type BusinessMetricsType struct {
	basetypes.ObjectType
}

func (t BusinessMetricsType) Equal(o attr.Type) bool {
	other, ok := o.(BusinessMetricsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t BusinessMetricsType) String() string {
	return "BusinessMetricsType"
}

func (t BusinessMetricsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	costReportTokensWithMetadataAttribute, ok := attributes["cost_report_tokens_with_metadata"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cost_report_tokens_with_metadata is missing from object`)

		return nil, diags
	}

	costReportTokensWithMetadataVal, ok := costReportTokensWithMetadataAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cost_report_tokens_with_metadata expected to be basetypes.ListValue, was: %T`, costReportTokensWithMetadataAttribute))
	}

	createdByTokenAttribute, ok := attributes["created_by_token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_by_token is missing from object`)

		return nil, diags
	}

	createdByTokenVal, ok := createdByTokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_by_token expected to be basetypes.StringValue, was: %T`, createdByTokenAttribute))
	}

	titleAttribute, ok := attributes["title"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`title is missing from object`)

		return nil, diags
	}

	titleVal, ok := titleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`title expected to be basetypes.StringValue, was: %T`, titleAttribute))
	}

	tokenAttribute, ok := attributes["token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`token is missing from object`)

		return nil, diags
	}

	tokenVal, ok := tokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`token expected to be basetypes.StringValue, was: %T`, tokenAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return BusinessMetricsValue{
		CostReportTokensWithMetadata: costReportTokensWithMetadataVal,
		CreatedByToken:               createdByTokenVal,
		Title:                        titleVal,
		Token:                        tokenVal,
		state:                        attr.ValueStateKnown,
	}, diags
}

func NewBusinessMetricsValueNull() BusinessMetricsValue {
	return BusinessMetricsValue{
		state: attr.ValueStateNull,
	}
}

func NewBusinessMetricsValueUnknown() BusinessMetricsValue {
	return BusinessMetricsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewBusinessMetricsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (BusinessMetricsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing BusinessMetricsValue Attribute Value",
				"While creating a BusinessMetricsValue value, a missing attribute value was detected. "+
					"A BusinessMetricsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("BusinessMetricsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid BusinessMetricsValue Attribute Type",
				"While creating a BusinessMetricsValue value, an invalid attribute value was detected. "+
					"A BusinessMetricsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("BusinessMetricsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("BusinessMetricsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra BusinessMetricsValue Attribute Value",
				"While creating a BusinessMetricsValue value, an extra attribute value was detected. "+
					"A BusinessMetricsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra BusinessMetricsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewBusinessMetricsValueUnknown(), diags
	}

	costReportTokensWithMetadataAttribute, ok := attributes["cost_report_tokens_with_metadata"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cost_report_tokens_with_metadata is missing from object`)

		return NewBusinessMetricsValueUnknown(), diags
	}

	costReportTokensWithMetadataVal, ok := costReportTokensWithMetadataAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cost_report_tokens_with_metadata expected to be basetypes.ListValue, was: %T`, costReportTokensWithMetadataAttribute))
	}

	createdByTokenAttribute, ok := attributes["created_by_token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_by_token is missing from object`)

		return NewBusinessMetricsValueUnknown(), diags
	}

	createdByTokenVal, ok := createdByTokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_by_token expected to be basetypes.StringValue, was: %T`, createdByTokenAttribute))
	}

	titleAttribute, ok := attributes["title"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`title is missing from object`)

		return NewBusinessMetricsValueUnknown(), diags
	}

	titleVal, ok := titleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`title expected to be basetypes.StringValue, was: %T`, titleAttribute))
	}

	tokenAttribute, ok := attributes["token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`token is missing from object`)

		return NewBusinessMetricsValueUnknown(), diags
	}

	tokenVal, ok := tokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`token expected to be basetypes.StringValue, was: %T`, tokenAttribute))
	}

	if diags.HasError() {
		return NewBusinessMetricsValueUnknown(), diags
	}

	return BusinessMetricsValue{
		CostReportTokensWithMetadata: costReportTokensWithMetadataVal,
		CreatedByToken:               createdByTokenVal,
		Title:                        titleVal,
		Token:                        tokenVal,
		state:                        attr.ValueStateKnown,
	}, diags
}

func NewBusinessMetricsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) BusinessMetricsValue {
	object, diags := NewBusinessMetricsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewBusinessMetricsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t BusinessMetricsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewBusinessMetricsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewBusinessMetricsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewBusinessMetricsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewBusinessMetricsValueMust(BusinessMetricsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t BusinessMetricsType) ValueType(ctx context.Context) attr.Value {
	return BusinessMetricsValue{}
}

var _ basetypes.ObjectValuable = BusinessMetricsValue{}

type BusinessMetricsValue struct {
	CostReportTokensWithMetadata basetypes.ListValue   `tfsdk:"cost_report_tokens_with_metadata"`
	CreatedByToken               basetypes.StringValue `tfsdk:"created_by_token"`
	Title                        basetypes.StringValue `tfsdk:"title"`
	Token                        basetypes.StringValue `tfsdk:"token"`
	state                        attr.ValueState
}

func (v BusinessMetricsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["cost_report_tokens_with_metadata"] = basetypes.ListType{
		ElemType: CostReportTokensWithMetadataValue{}.Type(ctx),
	}.TerraformType(ctx)
	attrTypes["created_by_token"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["title"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["token"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.CostReportTokensWithMetadata.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["cost_report_tokens_with_metadata"] = val

		val, err = v.CreatedByToken.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created_by_token"] = val

		val, err = v.Title.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["title"] = val

		val, err = v.Token.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["token"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v BusinessMetricsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v BusinessMetricsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v BusinessMetricsValue) String() string {
	return "BusinessMetricsValue"
}

func (v BusinessMetricsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	costReportTokensWithMetadata := types.ListValueMust(
		CostReportTokensWithMetadataType{
			basetypes.ObjectType{
				AttrTypes: CostReportTokensWithMetadataValue{}.AttributeTypes(ctx),
			},
		},
		v.CostReportTokensWithMetadata.Elements(),
	)

	if v.CostReportTokensWithMetadata.IsNull() {
		costReportTokensWithMetadata = types.ListNull(
			CostReportTokensWithMetadataType{
				basetypes.ObjectType{
					AttrTypes: CostReportTokensWithMetadataValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	if v.CostReportTokensWithMetadata.IsUnknown() {
		costReportTokensWithMetadata = types.ListUnknown(
			CostReportTokensWithMetadataType{
				basetypes.ObjectType{
					AttrTypes: CostReportTokensWithMetadataValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	attributeTypes := map[string]attr.Type{
		"cost_report_tokens_with_metadata": basetypes.ListType{
			ElemType: CostReportTokensWithMetadataValue{}.Type(ctx),
		},
		"created_by_token": basetypes.StringType{},
		"title":            basetypes.StringType{},
		"token":            basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"cost_report_tokens_with_metadata": costReportTokensWithMetadata,
			"created_by_token":                 v.CreatedByToken,
			"title":                            v.Title,
			"token":                            v.Token,
		})

	return objVal, diags
}

func (v BusinessMetricsValue) Equal(o attr.Value) bool {
	other, ok := o.(BusinessMetricsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.CostReportTokensWithMetadata.Equal(other.CostReportTokensWithMetadata) {
		return false
	}

	if !v.CreatedByToken.Equal(other.CreatedByToken) {
		return false
	}

	if !v.Title.Equal(other.Title) {
		return false
	}

	if !v.Token.Equal(other.Token) {
		return false
	}

	return true
}

func (v BusinessMetricsValue) Type(ctx context.Context) attr.Type {
	return BusinessMetricsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v BusinessMetricsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"cost_report_tokens_with_metadata": basetypes.ListType{
			ElemType: CostReportTokensWithMetadataValue{}.Type(ctx),
		},
		"created_by_token": basetypes.StringType{},
		"title":            basetypes.StringType{},
		"token":            basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = CostReportTokensWithMetadataType{}

type CostReportTokensWithMetadataType struct {
	basetypes.ObjectType
}

func (t CostReportTokensWithMetadataType) Equal(o attr.Type) bool {
	other, ok := o.(CostReportTokensWithMetadataType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t CostReportTokensWithMetadataType) String() string {
	return "CostReportTokensWithMetadataType"
}

func (t CostReportTokensWithMetadataType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	costReportTokenAttribute, ok := attributes["cost_report_token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cost_report_token is missing from object`)

		return nil, diags
	}

	costReportTokenVal, ok := costReportTokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cost_report_token expected to be basetypes.StringValue, was: %T`, costReportTokenAttribute))
	}

	labelFilterAttribute, ok := attributes["label_filter"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`label_filter is missing from object`)

		return nil, diags
	}

	labelFilterVal, ok := labelFilterAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`label_filter expected to be basetypes.ListValue, was: %T`, labelFilterAttribute))
	}

	unitScaleAttribute, ok := attributes["unit_scale"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`unit_scale is missing from object`)

		return nil, diags
	}

	unitScaleVal, ok := unitScaleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`unit_scale expected to be basetypes.StringValue, was: %T`, unitScaleAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return CostReportTokensWithMetadataValue{
		CostReportToken: costReportTokenVal,
		LabelFilter:     labelFilterVal,
		UnitScale:       unitScaleVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewCostReportTokensWithMetadataValueNull() CostReportTokensWithMetadataValue {
	return CostReportTokensWithMetadataValue{
		state: attr.ValueStateNull,
	}
}

func NewCostReportTokensWithMetadataValueUnknown() CostReportTokensWithMetadataValue {
	return CostReportTokensWithMetadataValue{
		state: attr.ValueStateUnknown,
	}
}

func NewCostReportTokensWithMetadataValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (CostReportTokensWithMetadataValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing CostReportTokensWithMetadataValue Attribute Value",
				"While creating a CostReportTokensWithMetadataValue value, a missing attribute value was detected. "+
					"A CostReportTokensWithMetadataValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CostReportTokensWithMetadataValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid CostReportTokensWithMetadataValue Attribute Type",
				"While creating a CostReportTokensWithMetadataValue value, an invalid attribute value was detected. "+
					"A CostReportTokensWithMetadataValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CostReportTokensWithMetadataValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("CostReportTokensWithMetadataValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra CostReportTokensWithMetadataValue Attribute Value",
				"While creating a CostReportTokensWithMetadataValue value, an extra attribute value was detected. "+
					"A CostReportTokensWithMetadataValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra CostReportTokensWithMetadataValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewCostReportTokensWithMetadataValueUnknown(), diags
	}

	costReportTokenAttribute, ok := attributes["cost_report_token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cost_report_token is missing from object`)

		return NewCostReportTokensWithMetadataValueUnknown(), diags
	}

	costReportTokenVal, ok := costReportTokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cost_report_token expected to be basetypes.StringValue, was: %T`, costReportTokenAttribute))
	}

	labelFilterAttribute, ok := attributes["label_filter"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`label_filter is missing from object`)

		return NewCostReportTokensWithMetadataValueUnknown(), diags
	}

	labelFilterVal, ok := labelFilterAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`label_filter expected to be basetypes.ListValue, was: %T`, labelFilterAttribute))
	}

	unitScaleAttribute, ok := attributes["unit_scale"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`unit_scale is missing from object`)

		return NewCostReportTokensWithMetadataValueUnknown(), diags
	}

	unitScaleVal, ok := unitScaleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`unit_scale expected to be basetypes.StringValue, was: %T`, unitScaleAttribute))
	}

	if diags.HasError() {
		return NewCostReportTokensWithMetadataValueUnknown(), diags
	}

	return CostReportTokensWithMetadataValue{
		CostReportToken: costReportTokenVal,
		LabelFilter:     labelFilterVal,
		UnitScale:       unitScaleVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewCostReportTokensWithMetadataValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) CostReportTokensWithMetadataValue {
	object, diags := NewCostReportTokensWithMetadataValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewCostReportTokensWithMetadataValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t CostReportTokensWithMetadataType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewCostReportTokensWithMetadataValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewCostReportTokensWithMetadataValueUnknown(), nil
	}

	if in.IsNull() {
		return NewCostReportTokensWithMetadataValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewCostReportTokensWithMetadataValueMust(CostReportTokensWithMetadataValue{}.AttributeTypes(ctx), attributes), nil
}

func (t CostReportTokensWithMetadataType) ValueType(ctx context.Context) attr.Value {
	return CostReportTokensWithMetadataValue{}
}

var _ basetypes.ObjectValuable = CostReportTokensWithMetadataValue{}

type CostReportTokensWithMetadataValue struct {
	CostReportToken basetypes.StringValue `tfsdk:"cost_report_token"`
	LabelFilter     basetypes.ListValue   `tfsdk:"label_filter"`
	UnitScale       basetypes.StringValue `tfsdk:"unit_scale"`
	state           attr.ValueState
}

func (v CostReportTokensWithMetadataValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["cost_report_token"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["label_filter"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["unit_scale"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.CostReportToken.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["cost_report_token"] = val

		val, err = v.LabelFilter.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["label_filter"] = val

		val, err = v.UnitScale.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["unit_scale"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v CostReportTokensWithMetadataValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v CostReportTokensWithMetadataValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v CostReportTokensWithMetadataValue) String() string {
	return "CostReportTokensWithMetadataValue"
}

func (v CostReportTokensWithMetadataValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var labelFilterVal basetypes.ListValue
	switch {
	case v.LabelFilter.IsUnknown():
		labelFilterVal = types.ListUnknown(types.StringType)
	case v.LabelFilter.IsNull():
		labelFilterVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		labelFilterVal, d = types.ListValue(types.StringType, v.LabelFilter.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"cost_report_token": basetypes.StringType{},
			"label_filter": basetypes.ListType{
				ElemType: types.StringType,
			},
			"unit_scale": basetypes.StringType{},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"cost_report_token": basetypes.StringType{},
		"label_filter": basetypes.ListType{
			ElemType: types.StringType,
		},
		"unit_scale": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"cost_report_token": v.CostReportToken,
			"label_filter":      labelFilterVal,
			"unit_scale":        v.UnitScale,
		})

	return objVal, diags
}

func (v CostReportTokensWithMetadataValue) Equal(o attr.Value) bool {
	other, ok := o.(CostReportTokensWithMetadataValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.CostReportToken.Equal(other.CostReportToken) {
		return false
	}

	if !v.LabelFilter.Equal(other.LabelFilter) {
		return false
	}

	if !v.UnitScale.Equal(other.UnitScale) {
		return false
	}

	return true
}

func (v CostReportTokensWithMetadataValue) Type(ctx context.Context) attr.Type {
	return CostReportTokensWithMetadataType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v CostReportTokensWithMetadataValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"cost_report_token": basetypes.StringType{},
		"label_filter": basetypes.ListType{
			ElemType: types.StringType,
		},
		"unit_scale": basetypes.StringType{},
	}
}
