// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_recommendation_views

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func RecommendationViewsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"recommendation_views": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"account_ids": schema.ListAttribute{
							ElementType:         types.StringType,
							Computed:            true,
							Description:         "Filter by cloud account identifiers.",
							MarkdownDescription: "Filter by cloud account identifiers.",
						},
						"billing_account_ids": schema.ListAttribute{
							ElementType:         types.StringType,
							Computed:            true,
							Description:         "Filter by billing account identifiers.",
							MarkdownDescription: "Filter by billing account identifiers.",
						},
						"created_at": schema.StringAttribute{
							Computed:            true,
							Description:         "The date and time, in UTC, the view was created. ISO 8601 Formatted.",
							MarkdownDescription: "The date and time, in UTC, the view was created. ISO 8601 Formatted.",
						},
						"created_by": schema.StringAttribute{
							Computed:            true,
							Description:         "The token for the Creator of this RecommendationView.",
							MarkdownDescription: "The token for the Creator of this RecommendationView.",
						},
						"end_date": schema.StringAttribute{
							Computed:            true,
							Description:         "Filter recommendations created on/before this YYYY-MM-DD date.",
							MarkdownDescription: "Filter recommendations created on/before this YYYY-MM-DD date.",
						},
						"id": schema.StringAttribute{
							Computed:            true,
							Description:         "The id of the resource",
							MarkdownDescription: "The id of the resource",
						},
						"provider_ids": schema.ListAttribute{
							ElementType:         types.StringType,
							Computed:            true,
							Description:         "Filter by one or more providers.",
							MarkdownDescription: "Filter by one or more providers.",
						},
						"regions": schema.ListAttribute{
							ElementType:         types.StringType,
							Computed:            true,
							Description:         "Filter by region slugs (e.g. us-east-1, eastus, asia-east1).",
							MarkdownDescription: "Filter by region slugs (e.g. us-east-1, eastus, asia-east1).",
						},
						"start_date": schema.StringAttribute{
							Computed:            true,
							Description:         "Filter recommendations created on/after this YYYY-MM-DD date.",
							MarkdownDescription: "Filter recommendations created on/after this YYYY-MM-DD date.",
						},
						"tag_key": schema.StringAttribute{
							Computed:            true,
							Description:         "Filter by tag key (must be used with tag_value).",
							MarkdownDescription: "Filter by tag key (must be used with tag_value).",
						},
						"tag_value": schema.StringAttribute{
							Computed:            true,
							Description:         "Filter by tag value (requires tag_key).",
							MarkdownDescription: "Filter by tag value (requires tag_key).",
						},
						"title": schema.StringAttribute{
							Computed:            true,
							Description:         "The title of the RecommendationView.",
							MarkdownDescription: "The title of the RecommendationView.",
						},
						"token": schema.StringAttribute{
							Computed: true,
						},
						"workspace_token": schema.StringAttribute{
							Computed:            true,
							Description:         "The token for the Workspace the RecommendationView is a part of.",
							MarkdownDescription: "The token for the Workspace the RecommendationView is a part of.",
						},
					},
					CustomType: RecommendationViewsType{
						ObjectType: types.ObjectType{
							AttrTypes: RecommendationViewsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
		},
	}
}

type RecommendationViewsModel struct {
	RecommendationViews types.List `tfsdk:"recommendation_views"`
}

var _ basetypes.ObjectTypable = RecommendationViewsType{}

type RecommendationViewsType struct {
	basetypes.ObjectType
}

func (t RecommendationViewsType) Equal(o attr.Type) bool {
	other, ok := o.(RecommendationViewsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t RecommendationViewsType) String() string {
	return "RecommendationViewsType"
}

func (t RecommendationViewsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	accountIdsAttribute, ok := attributes["account_ids"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`account_ids is missing from object`)

		return nil, diags
	}

	accountIdsVal, ok := accountIdsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`account_ids expected to be basetypes.ListValue, was: %T`, accountIdsAttribute))
	}

	billingAccountIdsAttribute, ok := attributes["billing_account_ids"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`billing_account_ids is missing from object`)

		return nil, diags
	}

	billingAccountIdsVal, ok := billingAccountIdsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`billing_account_ids expected to be basetypes.ListValue, was: %T`, billingAccountIdsAttribute))
	}

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return nil, diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	createdByAttribute, ok := attributes["created_by"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_by is missing from object`)

		return nil, diags
	}

	createdByVal, ok := createdByAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_by expected to be basetypes.StringValue, was: %T`, createdByAttribute))
	}

	endDateAttribute, ok := attributes["end_date"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`end_date is missing from object`)

		return nil, diags
	}

	endDateVal, ok := endDateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`end_date expected to be basetypes.StringValue, was: %T`, endDateAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	providerIdsAttribute, ok := attributes["provider_ids"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`provider_ids is missing from object`)

		return nil, diags
	}

	providerIdsVal, ok := providerIdsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`provider_ids expected to be basetypes.ListValue, was: %T`, providerIdsAttribute))
	}

	regionsAttribute, ok := attributes["regions"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`regions is missing from object`)

		return nil, diags
	}

	regionsVal, ok := regionsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`regions expected to be basetypes.ListValue, was: %T`, regionsAttribute))
	}

	startDateAttribute, ok := attributes["start_date"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`start_date is missing from object`)

		return nil, diags
	}

	startDateVal, ok := startDateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`start_date expected to be basetypes.StringValue, was: %T`, startDateAttribute))
	}

	tagKeyAttribute, ok := attributes["tag_key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tag_key is missing from object`)

		return nil, diags
	}

	tagKeyVal, ok := tagKeyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tag_key expected to be basetypes.StringValue, was: %T`, tagKeyAttribute))
	}

	tagValueAttribute, ok := attributes["tag_value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tag_value is missing from object`)

		return nil, diags
	}

	tagValueVal, ok := tagValueAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tag_value expected to be basetypes.StringValue, was: %T`, tagValueAttribute))
	}

	titleAttribute, ok := attributes["title"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`title is missing from object`)

		return nil, diags
	}

	titleVal, ok := titleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`title expected to be basetypes.StringValue, was: %T`, titleAttribute))
	}

	tokenAttribute, ok := attributes["token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`token is missing from object`)

		return nil, diags
	}

	tokenVal, ok := tokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`token expected to be basetypes.StringValue, was: %T`, tokenAttribute))
	}

	workspaceTokenAttribute, ok := attributes["workspace_token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`workspace_token is missing from object`)

		return nil, diags
	}

	workspaceTokenVal, ok := workspaceTokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`workspace_token expected to be basetypes.StringValue, was: %T`, workspaceTokenAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return RecommendationViewsValue{
		AccountIds:        accountIdsVal,
		BillingAccountIds: billingAccountIdsVal,
		CreatedAt:         createdAtVal,
		CreatedBy:         createdByVal,
		EndDate:           endDateVal,
		Id:                idVal,
		ProviderIds:       providerIdsVal,
		Regions:           regionsVal,
		StartDate:         startDateVal,
		TagKey:            tagKeyVal,
		TagValue:          tagValueVal,
		Title:             titleVal,
		Token:             tokenVal,
		WorkspaceToken:    workspaceTokenVal,
		state:             attr.ValueStateKnown,
	}, diags
}

func NewRecommendationViewsValueNull() RecommendationViewsValue {
	return RecommendationViewsValue{
		state: attr.ValueStateNull,
	}
}

func NewRecommendationViewsValueUnknown() RecommendationViewsValue {
	return RecommendationViewsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewRecommendationViewsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (RecommendationViewsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing RecommendationViewsValue Attribute Value",
				"While creating a RecommendationViewsValue value, a missing attribute value was detected. "+
					"A RecommendationViewsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RecommendationViewsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid RecommendationViewsValue Attribute Type",
				"While creating a RecommendationViewsValue value, an invalid attribute value was detected. "+
					"A RecommendationViewsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RecommendationViewsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("RecommendationViewsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra RecommendationViewsValue Attribute Value",
				"While creating a RecommendationViewsValue value, an extra attribute value was detected. "+
					"A RecommendationViewsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra RecommendationViewsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewRecommendationViewsValueUnknown(), diags
	}

	accountIdsAttribute, ok := attributes["account_ids"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`account_ids is missing from object`)

		return NewRecommendationViewsValueUnknown(), diags
	}

	accountIdsVal, ok := accountIdsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`account_ids expected to be basetypes.ListValue, was: %T`, accountIdsAttribute))
	}

	billingAccountIdsAttribute, ok := attributes["billing_account_ids"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`billing_account_ids is missing from object`)

		return NewRecommendationViewsValueUnknown(), diags
	}

	billingAccountIdsVal, ok := billingAccountIdsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`billing_account_ids expected to be basetypes.ListValue, was: %T`, billingAccountIdsAttribute))
	}

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return NewRecommendationViewsValueUnknown(), diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	createdByAttribute, ok := attributes["created_by"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_by is missing from object`)

		return NewRecommendationViewsValueUnknown(), diags
	}

	createdByVal, ok := createdByAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_by expected to be basetypes.StringValue, was: %T`, createdByAttribute))
	}

	endDateAttribute, ok := attributes["end_date"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`end_date is missing from object`)

		return NewRecommendationViewsValueUnknown(), diags
	}

	endDateVal, ok := endDateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`end_date expected to be basetypes.StringValue, was: %T`, endDateAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewRecommendationViewsValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	providerIdsAttribute, ok := attributes["provider_ids"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`provider_ids is missing from object`)

		return NewRecommendationViewsValueUnknown(), diags
	}

	providerIdsVal, ok := providerIdsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`provider_ids expected to be basetypes.ListValue, was: %T`, providerIdsAttribute))
	}

	regionsAttribute, ok := attributes["regions"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`regions is missing from object`)

		return NewRecommendationViewsValueUnknown(), diags
	}

	regionsVal, ok := regionsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`regions expected to be basetypes.ListValue, was: %T`, regionsAttribute))
	}

	startDateAttribute, ok := attributes["start_date"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`start_date is missing from object`)

		return NewRecommendationViewsValueUnknown(), diags
	}

	startDateVal, ok := startDateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`start_date expected to be basetypes.StringValue, was: %T`, startDateAttribute))
	}

	tagKeyAttribute, ok := attributes["tag_key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tag_key is missing from object`)

		return NewRecommendationViewsValueUnknown(), diags
	}

	tagKeyVal, ok := tagKeyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tag_key expected to be basetypes.StringValue, was: %T`, tagKeyAttribute))
	}

	tagValueAttribute, ok := attributes["tag_value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tag_value is missing from object`)

		return NewRecommendationViewsValueUnknown(), diags
	}

	tagValueVal, ok := tagValueAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tag_value expected to be basetypes.StringValue, was: %T`, tagValueAttribute))
	}

	titleAttribute, ok := attributes["title"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`title is missing from object`)

		return NewRecommendationViewsValueUnknown(), diags
	}

	titleVal, ok := titleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`title expected to be basetypes.StringValue, was: %T`, titleAttribute))
	}

	tokenAttribute, ok := attributes["token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`token is missing from object`)

		return NewRecommendationViewsValueUnknown(), diags
	}

	tokenVal, ok := tokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`token expected to be basetypes.StringValue, was: %T`, tokenAttribute))
	}

	workspaceTokenAttribute, ok := attributes["workspace_token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`workspace_token is missing from object`)

		return NewRecommendationViewsValueUnknown(), diags
	}

	workspaceTokenVal, ok := workspaceTokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`workspace_token expected to be basetypes.StringValue, was: %T`, workspaceTokenAttribute))
	}

	if diags.HasError() {
		return NewRecommendationViewsValueUnknown(), diags
	}

	return RecommendationViewsValue{
		AccountIds:        accountIdsVal,
		BillingAccountIds: billingAccountIdsVal,
		CreatedAt:         createdAtVal,
		CreatedBy:         createdByVal,
		EndDate:           endDateVal,
		Id:                idVal,
		ProviderIds:       providerIdsVal,
		Regions:           regionsVal,
		StartDate:         startDateVal,
		TagKey:            tagKeyVal,
		TagValue:          tagValueVal,
		Title:             titleVal,
		Token:             tokenVal,
		WorkspaceToken:    workspaceTokenVal,
		state:             attr.ValueStateKnown,
	}, diags
}

func NewRecommendationViewsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) RecommendationViewsValue {
	object, diags := NewRecommendationViewsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewRecommendationViewsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t RecommendationViewsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewRecommendationViewsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewRecommendationViewsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewRecommendationViewsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewRecommendationViewsValueMust(RecommendationViewsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t RecommendationViewsType) ValueType(ctx context.Context) attr.Value {
	return RecommendationViewsValue{}
}

var _ basetypes.ObjectValuable = RecommendationViewsValue{}

type RecommendationViewsValue struct {
	AccountIds        basetypes.ListValue   `tfsdk:"account_ids"`
	BillingAccountIds basetypes.ListValue   `tfsdk:"billing_account_ids"`
	CreatedAt         basetypes.StringValue `tfsdk:"created_at"`
	CreatedBy         basetypes.StringValue `tfsdk:"created_by"`
	EndDate           basetypes.StringValue `tfsdk:"end_date"`
	Id                basetypes.StringValue `tfsdk:"id"`
	ProviderIds       basetypes.ListValue   `tfsdk:"provider_ids"`
	Regions           basetypes.ListValue   `tfsdk:"regions"`
	StartDate         basetypes.StringValue `tfsdk:"start_date"`
	TagKey            basetypes.StringValue `tfsdk:"tag_key"`
	TagValue          basetypes.StringValue `tfsdk:"tag_value"`
	Title             basetypes.StringValue `tfsdk:"title"`
	Token             basetypes.StringValue `tfsdk:"token"`
	WorkspaceToken    basetypes.StringValue `tfsdk:"workspace_token"`
	state             attr.ValueState
}

func (v RecommendationViewsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 14)

	var val tftypes.Value
	var err error

	attrTypes["account_ids"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["billing_account_ids"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["created_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["created_by"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["end_date"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["provider_ids"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["regions"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["start_date"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["tag_key"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["tag_value"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["title"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["token"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["workspace_token"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 14)

		val, err = v.AccountIds.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["account_ids"] = val

		val, err = v.BillingAccountIds.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["billing_account_ids"] = val

		val, err = v.CreatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created_at"] = val

		val, err = v.CreatedBy.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created_by"] = val

		val, err = v.EndDate.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["end_date"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.ProviderIds.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["provider_ids"] = val

		val, err = v.Regions.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["regions"] = val

		val, err = v.StartDate.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["start_date"] = val

		val, err = v.TagKey.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tag_key"] = val

		val, err = v.TagValue.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tag_value"] = val

		val, err = v.Title.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["title"] = val

		val, err = v.Token.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["token"] = val

		val, err = v.WorkspaceToken.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["workspace_token"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v RecommendationViewsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v RecommendationViewsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v RecommendationViewsValue) String() string {
	return "RecommendationViewsValue"
}

func (v RecommendationViewsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var accountIdsVal basetypes.ListValue
	switch {
	case v.AccountIds.IsUnknown():
		accountIdsVal = types.ListUnknown(types.StringType)
	case v.AccountIds.IsNull():
		accountIdsVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		accountIdsVal, d = types.ListValue(types.StringType, v.AccountIds.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"account_ids": basetypes.ListType{
				ElemType: types.StringType,
			},
			"billing_account_ids": basetypes.ListType{
				ElemType: types.StringType,
			},
			"created_at": basetypes.StringType{},
			"created_by": basetypes.StringType{},
			"end_date":   basetypes.StringType{},
			"id":         basetypes.StringType{},
			"provider_ids": basetypes.ListType{
				ElemType: types.StringType,
			},
			"regions": basetypes.ListType{
				ElemType: types.StringType,
			},
			"start_date":      basetypes.StringType{},
			"tag_key":         basetypes.StringType{},
			"tag_value":       basetypes.StringType{},
			"title":           basetypes.StringType{},
			"token":           basetypes.StringType{},
			"workspace_token": basetypes.StringType{},
		}), diags
	}

	var billingAccountIdsVal basetypes.ListValue
	switch {
	case v.BillingAccountIds.IsUnknown():
		billingAccountIdsVal = types.ListUnknown(types.StringType)
	case v.BillingAccountIds.IsNull():
		billingAccountIdsVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		billingAccountIdsVal, d = types.ListValue(types.StringType, v.BillingAccountIds.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"account_ids": basetypes.ListType{
				ElemType: types.StringType,
			},
			"billing_account_ids": basetypes.ListType{
				ElemType: types.StringType,
			},
			"created_at": basetypes.StringType{},
			"created_by": basetypes.StringType{},
			"end_date":   basetypes.StringType{},
			"id":         basetypes.StringType{},
			"provider_ids": basetypes.ListType{
				ElemType: types.StringType,
			},
			"regions": basetypes.ListType{
				ElemType: types.StringType,
			},
			"start_date":      basetypes.StringType{},
			"tag_key":         basetypes.StringType{},
			"tag_value":       basetypes.StringType{},
			"title":           basetypes.StringType{},
			"token":           basetypes.StringType{},
			"workspace_token": basetypes.StringType{},
		}), diags
	}

	var providerIdsVal basetypes.ListValue
	switch {
	case v.ProviderIds.IsUnknown():
		providerIdsVal = types.ListUnknown(types.StringType)
	case v.ProviderIds.IsNull():
		providerIdsVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		providerIdsVal, d = types.ListValue(types.StringType, v.ProviderIds.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"account_ids": basetypes.ListType{
				ElemType: types.StringType,
			},
			"billing_account_ids": basetypes.ListType{
				ElemType: types.StringType,
			},
			"created_at": basetypes.StringType{},
			"created_by": basetypes.StringType{},
			"end_date":   basetypes.StringType{},
			"id":         basetypes.StringType{},
			"provider_ids": basetypes.ListType{
				ElemType: types.StringType,
			},
			"regions": basetypes.ListType{
				ElemType: types.StringType,
			},
			"start_date":      basetypes.StringType{},
			"tag_key":         basetypes.StringType{},
			"tag_value":       basetypes.StringType{},
			"title":           basetypes.StringType{},
			"token":           basetypes.StringType{},
			"workspace_token": basetypes.StringType{},
		}), diags
	}

	var regionsVal basetypes.ListValue
	switch {
	case v.Regions.IsUnknown():
		regionsVal = types.ListUnknown(types.StringType)
	case v.Regions.IsNull():
		regionsVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		regionsVal, d = types.ListValue(types.StringType, v.Regions.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"account_ids": basetypes.ListType{
				ElemType: types.StringType,
			},
			"billing_account_ids": basetypes.ListType{
				ElemType: types.StringType,
			},
			"created_at": basetypes.StringType{},
			"created_by": basetypes.StringType{},
			"end_date":   basetypes.StringType{},
			"id":         basetypes.StringType{},
			"provider_ids": basetypes.ListType{
				ElemType: types.StringType,
			},
			"regions": basetypes.ListType{
				ElemType: types.StringType,
			},
			"start_date":      basetypes.StringType{},
			"tag_key":         basetypes.StringType{},
			"tag_value":       basetypes.StringType{},
			"title":           basetypes.StringType{},
			"token":           basetypes.StringType{},
			"workspace_token": basetypes.StringType{},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"account_ids": basetypes.ListType{
			ElemType: types.StringType,
		},
		"billing_account_ids": basetypes.ListType{
			ElemType: types.StringType,
		},
		"created_at": basetypes.StringType{},
		"created_by": basetypes.StringType{},
		"end_date":   basetypes.StringType{},
		"id":         basetypes.StringType{},
		"provider_ids": basetypes.ListType{
			ElemType: types.StringType,
		},
		"regions": basetypes.ListType{
			ElemType: types.StringType,
		},
		"start_date":      basetypes.StringType{},
		"tag_key":         basetypes.StringType{},
		"tag_value":       basetypes.StringType{},
		"title":           basetypes.StringType{},
		"token":           basetypes.StringType{},
		"workspace_token": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"account_ids":         accountIdsVal,
			"billing_account_ids": billingAccountIdsVal,
			"created_at":          v.CreatedAt,
			"created_by":          v.CreatedBy,
			"end_date":            v.EndDate,
			"id":                  v.Id,
			"provider_ids":        providerIdsVal,
			"regions":             regionsVal,
			"start_date":          v.StartDate,
			"tag_key":             v.TagKey,
			"tag_value":           v.TagValue,
			"title":               v.Title,
			"token":               v.Token,
			"workspace_token":     v.WorkspaceToken,
		})

	return objVal, diags
}

func (v RecommendationViewsValue) Equal(o attr.Value) bool {
	other, ok := o.(RecommendationViewsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.AccountIds.Equal(other.AccountIds) {
		return false
	}

	if !v.BillingAccountIds.Equal(other.BillingAccountIds) {
		return false
	}

	if !v.CreatedAt.Equal(other.CreatedAt) {
		return false
	}

	if !v.CreatedBy.Equal(other.CreatedBy) {
		return false
	}

	if !v.EndDate.Equal(other.EndDate) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.ProviderIds.Equal(other.ProviderIds) {
		return false
	}

	if !v.Regions.Equal(other.Regions) {
		return false
	}

	if !v.StartDate.Equal(other.StartDate) {
		return false
	}

	if !v.TagKey.Equal(other.TagKey) {
		return false
	}

	if !v.TagValue.Equal(other.TagValue) {
		return false
	}

	if !v.Title.Equal(other.Title) {
		return false
	}

	if !v.Token.Equal(other.Token) {
		return false
	}

	if !v.WorkspaceToken.Equal(other.WorkspaceToken) {
		return false
	}

	return true
}

func (v RecommendationViewsValue) Type(ctx context.Context) attr.Type {
	return RecommendationViewsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v RecommendationViewsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"account_ids": basetypes.ListType{
			ElemType: types.StringType,
		},
		"billing_account_ids": basetypes.ListType{
			ElemType: types.StringType,
		},
		"created_at": basetypes.StringType{},
		"created_by": basetypes.StringType{},
		"end_date":   basetypes.StringType{},
		"id":         basetypes.StringType{},
		"provider_ids": basetypes.ListType{
			ElemType: types.StringType,
		},
		"regions": basetypes.ListType{
			ElemType: types.StringType,
		},
		"start_date":      basetypes.StringType{},
		"tag_key":         basetypes.StringType{},
		"tag_value":       basetypes.StringType{},
		"title":           basetypes.StringType{},
		"token":           basetypes.StringType{},
		"workspace_token": basetypes.StringType{},
	}
}
