// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_budget_alert

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func BudgetAlertResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"budget_tokens": schema.ListAttribute{
				ElementType:         types.StringType,
				Required:            true,
				Description:         "The tokens of the Budget that has the alert.",
				MarkdownDescription: "The tokens of the Budget that has the alert.",
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "The date and time, in UTC, the Budget Alert was created. ISO 8601 Formatted.",
				MarkdownDescription: "The date and time, in UTC, the Budget Alert was created. ISO 8601 Formatted.",
			},
			"duration_in_days": schema.StringAttribute{
				Required:            true,
				Description:         "The number of days from the start or end of the month to trigger the alert if the threshold is reached.  For the full month, pass an empty value.",
				MarkdownDescription: "The number of days from the start or end of the month to trigger the alert if the threshold is reached.  For the full month, pass an empty value.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The id of the budget alert",
				MarkdownDescription: "The id of the budget alert",
			},
			"integration_provider": schema.StringAttribute{
				Computed:            true,
				Description:         "The provider used for sending alerts. This must be configured in the console. Possible values are: slack, microsoft_graph.",
				MarkdownDescription: "The provider used for sending alerts. This must be configured in the console. Possible values are: slack, microsoft_graph.",
			},
			"period_to_track": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The period tracked on the alert. Used with duration_in_days to determine the time window of the alert. Defaults to start_of_the_month if not passed. Possible values: start_of_the_month, end_of_the_month.",
				MarkdownDescription: "The period tracked on the alert. Used with duration_in_days to determine the time window of the alert. Defaults to start_of_the_month if not passed. Possible values: start_of_the_month, end_of_the_month.",
			},
			"recipient_channels": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "The channels receiving the alerts. Requires an integration provider to be connected.",
				MarkdownDescription: "The channels receiving the alerts. Requires an integration provider to be connected.",
			},
			"recipient_emails": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "Email addresses that receive the alert. Must be organization users or addresses on a verified domain.",
				MarkdownDescription: "Email addresses that receive the alert. Must be organization users or addresses on a verified domain.",
			},
			"threshold": schema.Int64Attribute{
				Required:            true,
				Description:         "The threshold amount that must be met for the alert to fire.",
				MarkdownDescription: "The threshold amount that must be met for the alert to fire.",
			},
			"token": schema.StringAttribute{
				Computed:            true,
				Description:         "The token of the budget alert",
				MarkdownDescription: "The token of the budget alert",
			},
			"user_token": schema.StringAttribute{
				Computed:            true,
				Description:         "The token for the User who created this BudgetAlert.",
				MarkdownDescription: "The token for the User who created this BudgetAlert.",
			},
			"user_tokens": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "The tokens of the users that receive the alert.",
				MarkdownDescription: "The tokens of the users that receive the alert.",
			},
			"workspace_token": schema.StringAttribute{
				Computed:            true,
				Description:         "The token for the Workspace the ResourceReport is a part of.",
				MarkdownDescription: "The token for the Workspace the ResourceReport is a part of.",
			},
		},
	}
}

type BudgetAlertModel struct {
	BudgetTokens        types.List   `tfsdk:"budget_tokens"`
	CreatedAt           types.String `tfsdk:"created_at"`
	DurationInDays      types.String `tfsdk:"duration_in_days"`
	Id                  types.String `tfsdk:"id"`
	IntegrationProvider types.String `tfsdk:"integration_provider"`
	PeriodToTrack       types.String `tfsdk:"period_to_track"`
	RecipientChannels   types.List   `tfsdk:"recipient_channels"`
	RecipientEmails     types.List   `tfsdk:"recipient_emails"`
	Threshold           types.Int64  `tfsdk:"threshold"`
	Token               types.String `tfsdk:"token"`
	UserToken           types.String `tfsdk:"user_token"`
	UserTokens          types.List   `tfsdk:"user_tokens"`
	WorkspaceToken      types.String `tfsdk:"workspace_token"`
}
