// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_canvases

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func CanvasesResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "The date and time, in UTC, the Canvas was created. ISO 8601 Formatted.",
				MarkdownDescription: "The date and time, in UTC, the Canvas was created. ISO 8601 Formatted.",
			},
			"data": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"error": schema.StringAttribute{
						Computed:            true,
						Description:         "Error message if the refresh workflow failed. Read-only.",
						MarkdownDescription: "Error message if the refresh workflow failed. Read-only.",
					},
					"table": schema.SingleNestedAttribute{
						Attributes: map[string]schema.Attribute{},
						CustomType: TableType{
							ObjectType: types.ObjectType{
								AttrTypes: TableValue{}.AttributeTypes(ctx),
							},
						},
						Computed: true,
					},
				},
				CustomType: DataType{
					ObjectType: types.ObjectType{
						AttrTypes: DataValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The id of the canvas",
				MarkdownDescription: "The id of the canvas",
			},
			"prompt": schema.StringAttribute{
				Required:            true,
				Description:         "The prompt used to generate the Canvas.",
				MarkdownDescription: "The prompt used to generate the Canvas.",
			},
			"title": schema.StringAttribute{
				Required:            true,
				Description:         "The title of the Canvas.",
				MarkdownDescription: "The title of the Canvas.",
			},
			"token": schema.StringAttribute{
				Computed:            true,
				Description:         "The token of the canvas",
				MarkdownDescription: "The token of the canvas",
			},
			"updated_at": schema.StringAttribute{
				Computed:            true,
				Description:         "The date and time, in UTC, the Canvas was last updated. ISO 8601 Formatted.",
				MarkdownDescription: "The date and time, in UTC, the Canvas was last updated. ISO 8601 Formatted.",
			},
			"workspace_token": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The token of the Workspace to add the Canvas to. Required if the API token is associated with multiple Workspaces.",
				MarkdownDescription: "The token of the Workspace to add the Canvas to. Required if the API token is associated with multiple Workspaces.",
			},
		},
	}
}

type CanvasesModel struct {
	CreatedAt      types.String `tfsdk:"created_at"`
	Data           DataValue    `tfsdk:"data"`
	Id             types.String `tfsdk:"id"`
	Prompt         types.String `tfsdk:"prompt"`
	Title          types.String `tfsdk:"title"`
	Token          types.String `tfsdk:"token"`
	UpdatedAt      types.String `tfsdk:"updated_at"`
	WorkspaceToken types.String `tfsdk:"workspace_token"`
}

var _ basetypes.ObjectTypable = DataType{}

type DataType struct {
	basetypes.ObjectType
}

func (t DataType) Equal(o attr.Type) bool {
	other, ok := o.(DataType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DataType) String() string {
	return "DataType"
}

func (t DataType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	errorAttribute, ok := attributes["error"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`error is missing from object`)

		return nil, diags
	}

	errorVal, ok := errorAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`error expected to be basetypes.StringValue, was: %T`, errorAttribute))
	}

	tableAttribute, ok := attributes["table"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`table is missing from object`)

		return nil, diags
	}

	tableVal, ok := tableAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`table expected to be basetypes.ObjectValue, was: %T`, tableAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return DataValue{
		Error: errorVal,
		Table: tableVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewDataValueNull() DataValue {
	return DataValue{
		state: attr.ValueStateNull,
	}
}

func NewDataValueUnknown() DataValue {
	return DataValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDataValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DataValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing DataValue Attribute Value",
				"While creating a DataValue value, a missing attribute value was detected. "+
					"A DataValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DataValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid DataValue Attribute Type",
				"While creating a DataValue value, an invalid attribute value was detected. "+
					"A DataValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DataValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("DataValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra DataValue Attribute Value",
				"While creating a DataValue value, an extra attribute value was detected. "+
					"A DataValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra DataValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDataValueUnknown(), diags
	}

	errorAttribute, ok := attributes["error"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`error is missing from object`)

		return NewDataValueUnknown(), diags
	}

	errorVal, ok := errorAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`error expected to be basetypes.StringValue, was: %T`, errorAttribute))
	}

	tableAttribute, ok := attributes["table"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`table is missing from object`)

		return NewDataValueUnknown(), diags
	}

	tableVal, ok := tableAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`table expected to be basetypes.ObjectValue, was: %T`, tableAttribute))
	}

	if diags.HasError() {
		return NewDataValueUnknown(), diags
	}

	return DataValue{
		Error: errorVal,
		Table: tableVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewDataValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DataValue {
	object, diags := NewDataValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewDataValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DataType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDataValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDataValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDataValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDataValueMust(DataValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DataType) ValueType(ctx context.Context) attr.Value {
	return DataValue{}
}

var _ basetypes.ObjectValuable = DataValue{}

type DataValue struct {
	Error basetypes.StringValue `tfsdk:"error"`
	Table basetypes.ObjectValue `tfsdk:"table"`
	state attr.ValueState
}

func (v DataValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["error"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["table"] = basetypes.ObjectType{
		AttrTypes: TableValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Error.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["error"] = val

		val, err = v.Table.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["table"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DataValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DataValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DataValue) String() string {
	return "DataValue"
}

func (v DataValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var table basetypes.ObjectValue

	if v.Table.IsNull() {
		table = types.ObjectNull(
			TableValue{}.AttributeTypes(ctx),
		)
	}

	if v.Table.IsUnknown() {
		table = types.ObjectUnknown(
			TableValue{}.AttributeTypes(ctx),
		)
	}

	if !v.Table.IsNull() && !v.Table.IsUnknown() {
		table = types.ObjectValueMust(
			TableValue{}.AttributeTypes(ctx),
			v.Table.Attributes(),
		)
	}

	attributeTypes := map[string]attr.Type{
		"error": basetypes.StringType{},
		"table": basetypes.ObjectType{
			AttrTypes: TableValue{}.AttributeTypes(ctx),
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"error": v.Error,
			"table": table,
		})

	return objVal, diags
}

func (v DataValue) Equal(o attr.Value) bool {
	other, ok := o.(DataValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Error.Equal(other.Error) {
		return false
	}

	if !v.Table.Equal(other.Table) {
		return false
	}

	return true
}

func (v DataValue) Type(ctx context.Context) attr.Type {
	return DataType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DataValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"error": basetypes.StringType{},
		"table": basetypes.ObjectType{
			AttrTypes: TableValue{}.AttributeTypes(ctx),
		},
	}
}

var _ basetypes.ObjectTypable = TableType{}

type TableType struct {
	basetypes.ObjectType
}

func (t TableType) Equal(o attr.Type) bool {
	other, ok := o.(TableType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t TableType) String() string {
	return "TableType"
}

func (t TableType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if diags.HasError() {
		return nil, diags
	}

	return TableValue{
		state: attr.ValueStateKnown,
	}, diags
}

func NewTableValueNull() TableValue {
	return TableValue{
		state: attr.ValueStateNull,
	}
}

func NewTableValueUnknown() TableValue {
	return TableValue{
		state: attr.ValueStateUnknown,
	}
}

func NewTableValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (TableValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing TableValue Attribute Value",
				"While creating a TableValue value, a missing attribute value was detected. "+
					"A TableValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TableValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid TableValue Attribute Type",
				"While creating a TableValue value, an invalid attribute value was detected. "+
					"A TableValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TableValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("TableValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra TableValue Attribute Value",
				"While creating a TableValue value, an extra attribute value was detected. "+
					"A TableValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra TableValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewTableValueUnknown(), diags
	}

	if diags.HasError() {
		return NewTableValueUnknown(), diags
	}

	return TableValue{
		state: attr.ValueStateKnown,
	}, diags
}

func NewTableValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) TableValue {
	object, diags := NewTableValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewTableValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t TableType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewTableValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewTableValueUnknown(), nil
	}

	if in.IsNull() {
		return NewTableValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewTableValueMust(TableValue{}.AttributeTypes(ctx), attributes), nil
}

func (t TableType) ValueType(ctx context.Context) attr.Value {
	return TableValue{}
}

var _ basetypes.ObjectValuable = TableValue{}

type TableValue struct {
	state attr.ValueState
}

func (v TableValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 0)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 0)

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v TableValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v TableValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v TableValue) String() string {
	return "TableValue"
}

func (v TableValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{})

	return objVal, diags
}

func (v TableValue) Equal(o attr.Value) bool {
	other, ok := o.(TableValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	return true
}

func (v TableValue) Type(ctx context.Context) attr.Type {
	return TableType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v TableValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{}
}
