name: Test

on:
  push:
    branches:
      - main
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Run Tests
      run: go test ./...

    - name: Run Acceptance Tests
      run: TF_ACC=1 go test -v ./vantage